### ISSUE TITLE
Upgrade of SQLite database from 0.5 to 0.6 fails

### ISSUE THREAD

**Issue by mbirth** [gogits/gogs#1319]
I'm running Gogs via the [codeskyblue/docker-gogs](https://github.com/codeskyblue/docker-gogs) image on my Synology NAS. The version was 0.5.13.0214 Beta until I decided to update to the latest revision (0.6.1.0325 Beta) today.

Upon launch, it fails with the following error:

```
[I] Migration: generate collaboration from access
panic: reflect.Value.Convert: value of type interface {} cannot be converted to type time.Time

goroutine 1 [running]:
reflect.Value.Convert(0xb2d920, 0xc20823f490, 0xd4, 0x7f8f78a5f5d8, 0xd23c00, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:2137 +0x1eb
github.com/go-xorm/xorm.reflect2value(0xc2081dbe60, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/go-xorm/xorm/helpers.go:137 +0x901
github.com/go-xorm/xorm.value2Bytes(0xc2081dbe60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/go-xorm/xorm/helpers.go:160 +0x67
github.com/go-xorm/xorm.row2map(0xc2081dbd60, 0xc20810cf40, 0x4, 0x4, 0x0, 0x0, 0x0)
	/gopath/src/github.com/go-xorm/xorm/helpers.go:227 +0x3a1
github.com/go-xorm/xorm.rows2maps(0xc2081dbd60, 0x0, 0x0, 0x0, 0x0, 0x0)
	/gopath/src/github.com/go-xorm/xorm/helpers.go:198 +0x12d
github.com/go-xorm/xorm.(*Session).innerQuery(0xc20822db00, 0xc2081da9e0, 0xf0aad0, 0x8f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/go-xorm/xorm/session.go:1988 +0x252
github.com/go-xorm/xorm.(*Session).query(0xc20822db00, 0xf0aad0, 0x8f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/go-xorm/xorm/session.go:1954 +0x197
github.com/go-xorm/xorm.(*Session).Query(0xc20822db00, 0xf0aad0, 0x8f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/go-xorm/xorm/session.go:1998 +0x13f
github.com/go-xorm/xorm.(*Engine).Query(0xc2081dc7e0, 0xf0aad0, 0x8f, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/gopath/src/github.com/go-xorm/xorm/engine.go:1270 +0x122
github.com/gogits/gogs/models/migrations.accessToCollaboration(0xc2081dc7e0, 0x0, 0x0)
	/gopath/src/github.com/gogits/gogs/models/migrations/migrations.go:129 +0x2a6
github.com/gogits/gogs/models/migrations.(*migration).Migrate(0xc20800af80, 0xc2081dc7e0, 0x0, 0x0)
	/gopath/src/github.com/gogits/gogs/models/migrations/migrations.go:41 +0x43
github.com/gogits/gogs/models/migrations.Migrate(0xc2081dc7e0, 0x0, 0x0)
	/gopath/src/github.com/gogits/gogs/models/migrations/migrations.go:99 +0x862
github.com/gogits/gogs/models.NewEngine(0x0, 0x0)
	/gopath/src/github.com/gogits/gogs/models/models.go:164 +0x65
github.com/gogits/gogs/routers.GlobalInit()
	/gopath/src/github.com/gogits/gogs/routers/install.go:64 +0x1fc
github.com/gogits/gogs/cmd.runWeb(0xc20815a2a0)
	/gopath/src/github.com/gogits/gogs/cmd/web.go:182 +0xb4
github.com/codegangsta/cli.Command.Run(0xd63e00, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdc3e30, 0x15, 0xe9a150, ...)
	/gopath/src/github.com/codegangsta/cli/command.go:118 +0x104b
github.com/codegangsta/cli.(*App).Run(0xc20800c0f0, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
	/gopath/src/github.com/codegangsta/cli/app.go:154 +0xd04
main.main()
	/gopath/src/github.com/gogits/gogs/gogs.go:40 +0x367

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2080435c0)
	/gopath/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
	/gopath/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 7 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
	/gopath/src/github.com/gogits/gogs/modules/mailer/mailer.go:53 +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
	/gopath/src/github.com/gogits/gogs/modules/mailer/mailer.go:47 +0xea

goroutine 8 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208177a00)
	/gopath/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
	/gopath/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 26 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208226140)
	/usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 49 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
```

This is my `app.ini`:

```
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE = sqlite3
HOST = 127.0.0.1:3306
NAME = gogs
USER = root
PASSWD = 
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = /home/git/gogs-repositories

[server]
DOMAIN = …
SSH_PORT = 10022
HTTP_PORT = 3000
ROOT_URL = http://…

[session]
PROVIDER = file

[log]
MODE = file

[security]
INSTALL_LOCK = true
SECRET_KEY = …
```

**Comment by lhw** [comment]
It seems to be a problem with the sqlite3 library version used in that specific build from codeskyblue. I rebuild an image with the v0.6.1 tag and the migration went through without errors.

**Comment by codeskyblue** [comment]
I tested with my ubuntu machine. with gogs sqlite on docker:codeskyblue/docker-gogs. But it seems ok. Look I can see the version.
![image](https://cloud.githubusercontent.com/assets/3281689/8208972/fac15a9c-153c-11e5-863a-74fb3b47e633.png)

**Comment by mbirth** [comment]
I updated the Dockerfile with the current version and now the upgrade worked just fine. Thank you!
