### ISSUE TITLE
Problem to use redis

### ISSUE THREAD

**Issue by gustavopaes** [gogits/gogs#1472]
Hi,

I am trying to use Redis to cache, but I get this error:

```
gogs@gustavopaes:~/go/src/github.com/gogits/gogs$ ./gogs web
2015/08/12 06:15:58 [T] Custom path: /home/gogs/go/src/github.com/gogits/gogs/custom
2015/08/12 06:15:58 [T] Log path: /home/gogs/go/src/github.com/gogits/gogs/log
2015/08/12 06:15:58 [I] GIT GustavoPaes.Net 0.6.4.0808 Beta
2015/08/12 06:15:58 [I] Log Mode: File(Info)
2015/08/12 06:15:58 [I] Redis Supported
2015/08/12 06:15:58 [I] Memcache Supported
2015/08/12 06:15:58 [I] Cache Service Enabled
2015/08/12 06:15:58 [I] Session Service Enabled
2015/08/12 06:15:58 [I] Mail Service Enabled
2015/08/12 06:15:58 [I] Register Mail Service Enabled
2015/08/12 06:15:58 [I] SQLite3 Supported
2015/08/12 06:15:58 [I] Run Mode: Production
panic: session/redis: unsupported option 'localhost'

goroutine 16 [running]:
runtime.panic(0x872a040, 0x978de2f0)
	/usr/local/go/src/pkg/runtime/panic.c:279 +0xe9
github.com/macaron-contrib/cache.Cacher(0x9775555c, 0x1, 0x1, 0x0, 0x0)
	/home/gogs/go/src/github.com/macaron-contrib/cache/cache.go:106 +0xf0
github.com/gogits/gogs/cmd.newMacaron(0x975b9700)
	/home/gogs/go/src/github.com/gogits/gogs/cmd/web.go:151 +0x994
github.com/gogits/gogs/cmd.runWeb(0x975b9700)
	/home/gogs/go/src/github.com/gogits/gogs/cmd/web.go:188 +0x91
github.com/codegangsta/cli.Command.Run(0x87c8428, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x883e3c8, 0x15, 0x88f0cc8, ...)
	/home/gogs/go/src/github.com/codegangsta/cli/command.go:127 +0xc7d
github.com/codegangsta/cli.(*App).Run(0x97591830, 0x9755a000, 0x2, 0x2, 0x0, 0x0)
	/home/gogs/go/src/github.com/codegangsta/cli/app.go:159 +0x9c3
main.main()
	/home/gogs/go/src/github.com/gogits/gogs/gogs.go:40 +0x222

goroutine 19 [finalizer wait]:
runtime.park(0x80f6170, 0x8d32a0c, 0x8c4ee29)
	/usr/local/go/src/pkg/runtime/proc.c:1369 +0x94
runtime.parkunlock(0x8d32a0c, 0x8c4ee29)
	/usr/local/go/src/pkg/runtime/proc.c:1385 +0x3f
runfinq()
	/usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xc5
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0x9760a660)
	/home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x245
created by github.com/gogits/gogs/modules/log.newLogger
	/home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0xce

goroutine 22 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
	/home/gogs/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:53 +0x5d
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
	/home/gogs/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:47 +0xc3

goroutine 23 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0x976abfa0)
	/home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x245
created by github.com/gogits/gogs/modules/log.newLogger
	/home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0xce

goroutine 37 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0x975e8900)
	/home/gogs/go/src/github.com/gogits/gogs/modules/cron/cron.go:162 +0x78f
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
	/home/gogs/go/src/github.com/gogits/gogs/modules/cron/cron.go:137 +0x39

goroutine 38 [chan receive]:
github.com/gogits/gogs/models.DeliverHooks()
	/home/gogs/go/src/github.com/gogits/gogs/models/webhook.go:408 +0x335
created by github.com/gogits/gogs/models.InitDeliverHooks
	/home/gogs/go/src/github.com/gogits/gogs/models/webhook.go:426 +0x28

goroutine 36 [chan receive]:
database/sql.(*DB).connectionOpener(0x976b5b00)
	/usr/local/go/src/pkg/database/sql/sql.go:583 +0x49
created by database/sql.Open
	/usr/local/go/src/pkg/database/sql/sql.go:442 +0x1e4

goroutine 33 [syscall]:
runtime.goexit()
	/usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 39 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0x976e1b40)
	/home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x245
created by github.com/gogits/gogs/modules/log.newLogger
	/home/gogs/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0xce
gogs@gustavopaes:~/go/src/github.com/gogits/gogs$ 
```

I think the key problem is this message:
    panic: session/redis: unsupported option 'localhost'

My `app.ini` is:
```
    [cache]
    ADAPTER = redis
    HOST = localhost:6379
```

I tried HOST = 127.0.0.1:6379 and didn't work too.

This problem occurs in master and develop branch.

**Comment by gustavopaes** [comment]
Ok, my bad. HOST actually is not just localhost, need to follow some rules:

    redis: network=tcp,addr=:6379,password=macaron,db=0,pool_size=100,idle_timeout=180

May be need to improve this doc:
http://gogs.io/docs/advanced/configuration_cheat_sheet.html#cache

**Comment by Unknwon** [comment]
Thanks @gustavopaes , good catch!

**Comment by Unknwon** [comment]
New docs has been pushed, website should be updated within 5 mins.

**Comment by gustavopaes** [comment]
Great. Thank you.
