### ISSUE TITLE
panic: length of langs is not same as length of names

### ISSUE THREAD

**Issue by mogudy** [gogits/gogs#1547]
Gogs version 0.6.5.0825 Beta

What I did before the error occurred:
1. Install & run gogs from source (via supervisor)
2. Register the first user
3. import repositories from local path
4. clone the repository to my working pc
5. change domain name in custom/conf/app.ini
6. restart service & it crashed forever then

Below is the log.

stdout.log
```
2015/08/27 22:44:56 [T] Custom path: /home/git/go/src/github.com/gogits/gogs/custom
2015/08/27 22:44:56 [T] Log path: /home/git/go/src/github.com/gogits/gogs/log
2015/08/27 22:44:56 [I] Gogs: Go Git Service 0.6.5.0825 Beta
2015/08/27 22:44:56 [I] Log Mode: Console(Trace)
2015/08/27 22:44:56 [I] Cache Service Enabled
2015/08/27 22:44:56 [I] Session Service Enabled
2015/08/27 22:44:56 [T] Doing: CheckRepoStats
2015/08/27 22:44:56 [I] Run Mode: Development
panic: length of langs is not same as length of names

goroutine 1 [running]:
github.com/macaron-contrib/i18n.prepareOptions(0xc208635020, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/git/go/src/github.com/macaron-contrib/i18n/i18n.go:117 +0x2ba
github.com/macaron-contrib/i18n.I18n(0xc208635020, 0x1, 0x1, 0x0, 0x0)
        /home/git/go/src/github.com/macaron-contrib/i18n/i18n.go:150 +0x85
github.com/gogits/gogs/cmd.newMacaron(0xc2081900f0)
        /home/git/go/src/github.com/gogits/gogs/cmd/web.go:146 +0xbad
github.com/gogits/gogs/cmd.runWeb(0xc2081900f0)
        /home/git/go/src/github.com/gogits/gogs/cmd/web.go:188 +0xbe
github.com/codegangsta/cli.Command.Run(0xd17e70, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd7a970, 0x15, 0xe568b0, ...)
        /home/git/go/src/github.com/codegangsta/cli/command.go:127 +0xffe
github.com/codegangsta/cli.(*App).Run(0xc208182d00, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /home/git/go/src/github.com/codegangsta/cli/app.go:159 +0xd7b
main.main()
        /home/git/go/src/github.com/gogits/gogs/gogs.go:40 +0x367

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208057800)
        /home/git/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/git/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 7 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
        /home/git/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:80 +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
        /home/git/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:74 +0xea

goroutine 8 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2081b1e80)
        /home/git/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/git/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 37 [chan receive]:
database/sql.(*DB).connectionOpener(0xc20826a5a0)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 53 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc20815da80)
        /home/git/go/src/github.com/gogits/gogs/modules/cron/cron.go:161 +0xa65
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
        /home/git/go/src/github.com/gogits/gogs/modules/cron/cron.go:136 +0x3d

goroutine 54 [chan receive]:
github.com/gogits/gogs/models.DeliverHooks()
        /home/git/go/src/github.com/gogits/gogs/models/webhook.go:408 +0x546
created by github.com/gogits/gogs/models.InitDeliverHooks
        /home/git/go/src/github.com/gogits/gogs/models/webhook.go:426 +0x25

goroutine 55 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2081e7e40)
        /home/git/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/git/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a
```

stderr.log
```
github.com/gogits/gogs/models.DeliverHooks()
        /home/git/go/src/github.com/gogits/gogs/models/webhook.go:408 +0x546
created by github.com/gogits/gogs/models.InitDeliverHooks
        /home/git/go/src/github.com/gogits/gogs/models/webhook.go:426 +0x25

goroutine 43 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2081e0900)
        /home/git/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/git/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a
```

**Comment by Unknwon** [comment]
Thanks your feedback!

Would you mind to dump your `custom/conf/app.ini` here? (mask some sensitive info of course)

**Comment by mogudy** [comment]
Thanks for your tips.

I did not realize that my Text Editor uses GBK as default encoding.

**Comment by Unknwon** [comment]
OK... No problem :blush:
