### ISSUE TITLE
It would be good that we can edit gogs' features of first page (log in/register) 

### ISSUE THREAD

**Issue by xxxtonixxx** [gogits/gogs#2098]
To add the translation to other languages and to can modify it or to delete it its content.

better a image!
![image]
(http://s29.postimg.org/h587q7ixj/issue.jpg)

:thumbsup:

**Comment by Unknwon** [comment]
You may want to turn this issue into `custom templates` support.

**Comment by xxxtonixxx** [comment]
Mmm, perhaps, It would be a good idea or to allow to add directly our customs css styles... but I say to add the translation of paragraph, it would be enought now :sweat_smile:

**Comment by Unknwon** [comment]
OK, I'll just turn into `custom templates` :smiling_imp:

**Comment by nanoant** [comment]
@xxxtonixxx Hmm... but `templates/` are editable already, there's nothing that stops you from altering the `home.tmpl` to suit you service needs.

This is what I do, and it works fine. So I don't see how the `custom templates` feature should work, given what we have now :)

Want a custom CSS add it to `public/` and add extra stylesheet entry in `templates/base/head.tmpl`.

**Comment by Unknwon** [comment]
Currently you would mess up with Git history...

**Comment by xxxtonixxx** [comment]
@nanoant Ok, I didn't know when it was those files and I could touch it... Thanks! 

Mmmm... @Unknwon, Is that to say it's more difficult?, I don't understand good that part, sorry!

And, if this is easy, It would be so good that it was documented! :+1:

**Comment by Unknwon** [comment]
@xxxtonixxx Yes I mean, you can edit template files like @nanoant pointed out, but those files are the ones Gogs may have change to, so now you could have conflict.

Custom option allows you keep your changes out of Gogs git history to avoid conflicts, just like the way custom app.ini, locale files works.

**Comment by xxxtonixxx** [comment]
Ok, thank you!

**Comment by Unknwon** [comment]
Alpha support for custom templates has been pushed to `develop` branch, you can put template file with same under your `custom/templates` directory.

Some warnings:

- Make as minimal changes as possible
- No guarantee for compatibility with future changes
- Do not rely on template variables as much as possible, just change static content is recommended

Example usage:

- Custom version of your home page (`home.tmpl`)
- Add additional content to head (`base/head.tmpl`) or footer (`base/footer.tmpl`)

**Comment by xxxtonixxx** [comment]
Ok, so thanks for this feature! :smile:

**Comment by richmahn** [comment]
@Unknwon Not sure if it make a new Issue or post here, but a custom/templates/base/head.tmpl doesn't work unless templates/base/head.tmpl is deleted, otherwise I get this error message when starting gogs:

`[git@test ~]$ gogs/gogs web
2016/03/25 12:54:33 [T] Custom path: /home/git/gogs/custom
2016/03/25 12:54:33 [T] Log path: /var/log/gogs
2016/03/25 12:54:33 [I] Door43 0.9.15.0323
2016/03/25 12:54:33 [I] Log Mode: File(Info)
2016/03/25 12:54:33 [I] Cache Service Enabled
2016/03/25 12:54:33 [I] Session Service Enabled
2016/03/25 12:54:33 [I] Mail Service Enabled
2016/03/25 12:54:33 [I] Register Mail Service Enabled
2016/03/25 12:54:33 [I] Notify Mail Service Enabled
2016/03/25 12:54:33 [I] Git Version: 1.8.3.1
2016/03/25 12:54:34 [I] Run Mode: Production
2016/03/25 12:54:34 [T] Doing: MirrorUpdate
2016/03/25 12:54:34 [T] Doing: GitFsck
2016/03/25 12:54:34 [T] Doing: CheckRepoStats
panic: template: base/head:158: unexpected EOF

goroutine 1 [running]:
panic(0xed2240, 0xc8203a9a20)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
html/template.Must(0x0, 0x7fcf0af62028, 0xc8203a9a20, 0x0)
        /usr/local/go/src/html/template/template.go:340 +0x4b
gopkg.in/macaron%2ev1.compile(0xc82032fb60, 0x18, 0xc8204c47f0, 0x1, 0x1, 0x0, 0x0, 0xc82032fbc0, 0x2, 0x2, ...)
        /home/git/go/src/gopkg.in/macaron.v1/render.go:281 +0x97e
gopkg.in/macaron%2ev1.(*templateSet).Set(0xc8202150e0, 0x105c5c0, 0x7, 0xc82046cff0, 0x0)
        /home/git/go/src/gopkg.in/macaron.v1/render.go:306 +0x4d
gopkg.in/macaron%2ev1.renderHandler(0xc82032fb60, 0x18, 0xc8204c47f0, 0x1, 0x1, 0x0, 0x0, 0xc82032fbc0, 0x2, 0x2, ...)
        /home/git/go/src/gopkg.in/macaron.v1/render.go:373 +0x217
gopkg.in/macaron%2ev1.Renderer(0xc820440c08, 0x1, 0x1, 0x0, 0x0)
        /home/git/go/src/gopkg.in/macaron.v1/render.go:410 +0x1f0
github.com/gogits/gogs/cmd.newMacaron(0xc8202a28c0)
        /home/git/go/src/github.com/gogits/gogs/cmd/web.go:131 +0x88d
github.com/gogits/gogs/cmd.runWeb(0xc8202a28c0)
        /home/git/go/src/github.com/gogits/gogs/cmd/web.go:185 +0xbb
github.com/codegangsta/cli.Command.Run(0x1068a88, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x11099f0, 0x15, 0x0, ...)
        /home/git/go/src/github.com/codegangsta/cli/command.go:174 +0x1399
github.com/codegangsta/cli.(*App).Run(0xc8202a2640, 0xc82000a1a0, 0x2, 0x2, 0x0, 0x0)
        /home/git/go/src/github.com/codegangsta/cli/app.go:187 +0x112b
main.main()
        /home/git/go/src/github.com/gogits/gogs/gogs.go:40 +0x368
`

**Comment by richmahn** [comment]
Oh, but if I remove templates/base/head.tmpl, it does start gogs, but then going to the home page I get:

html/template:home:1:11: no such template "base/head"

So it isn't looking i my custom directory for it. Is head.tmpl supported for custom templates?

**Comment by strk** [comment]
Thank you, works pretty nicely. Next we'll need custom translations (for the custom template contents :)

**Comment by Unknwon** [comment]
@strk https://gogs.io/docs/features/i18n

**Comment by strk** [comment]
Yes @Unknwon, thanks. But I was referring to localization within custom templates, but I figured how to deal with them: using `{{if eq .Lang "es-ES"}}` constructs (btw, `eq` might not be  the best way for it, see #2958)

**Comment by AddoSolutions** [comment]
This line is gold.

https://github.com/gogits/gogs/commit/d733efc1cc27739a386188e3aa02c8a524b06e8d#diff-da541ef36e39344f2e12bddd91d363e2R128

**Comment by AddoSolutions** [comment]
Sorry or the double post, but do we think it would be good to add `/custom` to the docker file?

https://github.com/gogits/gogs/blob/master/Dockerfile#L19

**Comment by bkcsoft** [comment]
Can't be done :D

**Comment by AddoSolutions** [comment]
Oh? Why is that? Or am I missing an obvious joke? 😂

**Comment by bkcsoft** [comment]
`/data` where custom is stored, is a volume, and because of that we can't
inject files in it :smile:

**Comment by AddoSolutions** [comment]
Oh, ok :) perfect, so I can still accomplish the same thing. I didn't realize that the full path technically is: `data/custom/templates` which is even cooler because then it's version controlled! :)

**Comment by Drahoslav7** [comment]
Support of custom templates is great. Will there be also support for custom public files?

Same logic could be used: First file is searching in ```./custom/public``` and then in ```./public```.

Or there might be some inteligent merging: For styles for example. File ```./custom/public/css/gogs.css``` could be concatenated to end of ```./public/css/gogs.css```. But this approach may not suits to all use cases well.

**Comment by strk** [comment]
This ticket is old and the feature in the subject is available already. Should be closed.
For custom public files, if still not supported, a new ticket would be more appropriate

**Comment by Caballerog** [comment]
+1
