### ISSUE TITLE
Can't start gogs with redis

### ISSUE THREAD

**Issue by garygreen** [gogits/gogs#2130]
When attempting to use redis as cache adapter it fails to start gogs.

```ini
ADAPTER = redis
HOST = network=tcp,addr=127.0.0.1:6379,db=0,pool_size=100,idle_timeout=180
```

The output when starting gogs:

```
2015/12/09 11:23:50 [T] Custom path: /home/git/gogs/custom
2015/12/09 11:23:50 [T] Log path: /home/git/gogs/log
2015/12/09 11:23:50 [I] Gogs: Go Git Service 0.7.33.1205 Beta
2015/12/09 11:23:50 [I] Log Mode: File(Info)
2015/12/09 11:23:50 [I] Cache Service Enabled
2015/12/09 11:23:50 [I] Session Service Enabled
2015/12/09 11:23:50 [I] Git Version: 1.8.3.1
2015/12/09 11:23:50 [T] Doing: CheckRepoStats
2015/12/09 11:23:50 [I] SQLite3 Supported
2015/12/09 11:23:50 [I] TiDB Supported
2015/12/09 11:23:50 [I] Run Mode: Production
[MySQL] 2015/12/09 11:23:50 statement.go:27: Invalid Connection
panic: error parsing idle timeout: time: invalid duration s

goroutine 1 [running]:
github.com/go-macaron/cache.Cacher(0xc820520698, 0x1, 0x1, 0x0, 0x0)
        /home/vagrant/go/src/github.com/go-macaron/cache/cache.go:104 +0x1a6
github.com/gogits/gogs/cmd.newMacaron(0xc820406000)
        /home/vagrant/go/src/github.com/gogits/gogs/cmd/web.go:150 +0xdbc
github.com/gogits/gogs/cmd.runWeb(0xc820406000)
        /home/vagrant/go/src/github.com/gogits/gogs/cmd/web.go:180 +0xc2
github.com/codegangsta/cli.Command.Run(0x15305d0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15ff2e0, 0x15, 0x1734940, ...)
        /home/vagrant/go/src/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/codegangsta/cli.(*App).Run(0xc8203d3d40, 0xc82000a0c0, 0x2, 0x2, 0x0, 0x0)
        /home/vagrant/go/src/github.com/codegangsta/cli/app.go:175 +0xfff
main.main()
        /home/vagrant/go/src/github.com/gogits/gogs/gogs.go:40 +0x35c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc820055cc0)
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

goroutine 19 [IO wait]:
net.runtime_pollWait(0x7f2e382cd440, 0x72, 0xc820010190)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820244b50, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820244b50, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820244af0, 0x0, 0x7f2e382cd538, 0xc820207200)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820028260, 0xc820049dd0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820028260, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8200154a0, 0x7f2e382cd500, 0xc820028260, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8200154a0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0x155a4f0, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1967 +0x8f
created by github.com/pingcap/tidb.init.2
        /home/vagrant/go/src/github.com/pingcap/tidb/tidb.go:363 +0x214

goroutine 22 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc82042edc0)
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

goroutine 32 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82042cfa0)
        /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 50 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc82028b540)
        /home/vagrant/go/src/github.com/gogits/gogs/modules/cron/cron.go:161 +0x9e8
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
        /home/vagrant/go/src/github.com/gogits/gogs/modules/cron/cron.go:136 +0x40

goroutine 51 [chan receive]:
github.com/gogits/gogs/models.DeliverHooks()
        /home/vagrant/go/src/github.com/gogits/gogs/models/webhook.go:600 +0x465
created by github.com/gogits/gogs/models.InitDeliverHooks
        /home/vagrant/go/src/github.com/gogits/gogs/models/webhook.go:620 +0x2b

goroutine 52 [chan receive]:
github.com/gogits/gogs/models.TestPullRequests()
        /home/vagrant/go/src/github.com/gogits/gogs/models/pull.go:540 +0x1de
created by github.com/gogits/gogs/models.InitTestPullRequests
        /home/vagrant/go/src/github.com/gogits/gogs/models/pull.go:558 +0x2b
goroutine 53 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc82059b740)
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138
[git@Centos-01 gogs]$ ./gogs web > test
panic: error parsing idle timeout: time: invalid duration s

goroutine 1 [running]:
github.com/go-macaron/cache.Cacher(0xc820682698, 0x1, 0x1, 0x0, 0x0)
        /home/vagrant/go/src/github.com/go-macaron/cache/cache.go:104 +0x1a6
github.com/gogits/gogs/cmd.newMacaron(0xc8203f2480)
        /home/vagrant/go/src/github.com/gogits/gogs/cmd/web.go:150 +0xdbc
github.com/gogits/gogs/cmd.runWeb(0xc8203f2480)
        /home/vagrant/go/src/github.com/gogits/gogs/cmd/web.go:180 +0xc2
github.com/codegangsta/cli.Command.Run(0x15305d0, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x15ff2e0, 0x15, 0x1734940, ...)
        /home/vagrant/go/src/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/codegangsta/cli.(*App).Run(0xc8203f2240, 0xc82000a0c0, 0x2, 0x2, 0x0, 0x0)
        /home/vagrant/go/src/github.com/codegangsta/cli/app.go:175 +0xfff
main.main()
        /home/vagrant/go/src/github.com/gogits/gogs/gogs.go:40 +0x35c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc820055cc0)
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

goroutine 19 [IO wait]:
net.runtime_pollWait(0x7fe1c430c7a8, 0x72, 0xc820010190)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203cd250, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203cd250, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8203cd1f0, 0x0, 0x7fe1c430c8a0, 0xc82038ae00)
        /usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820280148, 0xc820045dd0, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc820280148, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820282900, 0x7fe1c430c868, 0xc820280148, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820282900, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0x155a4f0, 0xe, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:1967 +0x8f
created by github.com/pingcap/tidb.init.2
        /home/vagrant/go/src/github.com/pingcap/tidb/tidb.go:363 +0x214

goroutine 10 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc820423e00)
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138

goroutine 37 [chan receive]:
database/sql.(*DB).connectionOpener(0xc82041bae0)
        /usr/local/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:481 +0x336

goroutine 67 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc82024c540)
        /home/vagrant/go/src/github.com/gogits/gogs/modules/cron/cron.go:161 +0x9e8
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
        /home/vagrant/go/src/github.com/gogits/gogs/modules/cron/cron.go:136 +0x40

goroutine 68 [chan receive]:
github.com/gogits/gogs/models.DeliverHooks()
        /home/vagrant/go/src/github.com/gogits/gogs/models/webhook.go:600 +0x465
created by github.com/gogits/gogs/models.InitDeliverHooks
        /home/vagrant/go/src/github.com/gogits/gogs/models/webhook.go:620 +0x2b

goroutine 69 [chan receive]:
github.com/gogits/gogs/models.TestPullRequests()
        /home/vagrant/go/src/github.com/gogits/gogs/models/pull.go:540 +0x1de
created by github.com/gogits/gogs/models.InitTestPullRequests
        /home/vagrant/go/src/github.com/gogits/gogs/models/pull.go:558 +0x2b

goroutine 70 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc82058f380)
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:235 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
        /home/vagrant/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x138
```

**Comment by Unknwon** [comment]
Thanks your feedback!

Please follow on https://github.com/gogits/gogs/issues/2115 , and this can be fixed by `go get -u gopkg.in/ini.v1`.
