### ISSUE TITLE
Doesn't work with SGit and maybe other jgit based clients

### ISSUE THREAD

**Issue by brimstone** [gogits/gogs#241]
I'm using [sgit](https://play.google.com/store/apps/details?id=me.sheimi.sgit) and get the following error when trying to clone a repo over http:

```
W/System.err(19460): org.eclipse.jgit.api.errors.TransportException: http://gogs:3000/user/repo.git: Starting read stage without written request data pending is not supported
W/System.err(19460):    at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:137)
W/System.err(19460):    at org.eclipse.jgit.api.CloneCommand.fetch(CloneCommand.java:178)
W/System.err(19460):    at org.eclipse.jgit.api.CloneCommand.call(CloneCommand.java:125)
W/System.err(19460):    at me.sheimi.sgit.repo.tasks.repo.CloneTask.cloneRepo(CloneTask.java:69)
W/System.err(19460):    at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:32)
W/System.err(19460):    at me.sheimi.sgit.repo.tasks.repo.CloneTask.doInBackground(CloneTask.java:1)
W/System.err(19460):    at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err(19460):    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(19460):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err(19460):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err(19460):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err(19460):    at java.lang.Thread.run(Thread.java:841)
```

**Comment by Unknwon** [comment]
Close for not but open for continuing discussion.
