### ISSUE TITLE
panic on pushing repository

### ISSUE THREAD

**Issue by mbentley** [gogits/gogs#2646]
When trying to push a repository for the first time, I am getting a panic:

```
$ git push -f gogs master
Username for 'https://try.gogs.io': mbentley
Password for 'https://mbentley@try.gogs.io':
Counting objects: 95, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (52/52), done.
Writing objects: 100% (95/95), 2.50 MiB | 1.38 MiB/s, done.
Total 95 (delta 33), reused 95 (delta 33)
remote: panic: runtime error: invalid memory address or nil pointer dereference
remote: [signal 0xb code=0x1 addr=0x18 pc=0x61545b]
remote:
remote: goroutine 1 [running]:
remote: github.com/gogits/gogs/modules/log.(*Logger).writerMsg(0x0, 0x0, 0x0, 0xc820259cb0, 0x21, 0x0, 0x0)
remote:         /home/git/gopath/src/github.com/gogits/gogs/modules/log/log.go:197 +0x4b
remote: github.com/gogits/gogs/modules/log.(*Logger).Trace(0x0, 0x1034ea0, 0x1d, 0x0, 0x0, 0x0)
remote:         /home/git/gopath/src/github.com/gogits/gogs/modules/log/log.go:279 +0xd0
remote: github.com/gogits/gogs/cmd.runUpdate(0xc820267b00)
remote:         /home/git/gopath/src/github.com/gogits/gogs/cmd/update.go:33 +0x100
remote: github.com/codegangsta/cli.Command.Run(0xf7e338, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1082e80, 0x2f, 0x1083000, ...)
remote:         /home/git/gopath/src/github.com/codegangsta/cli/command.go:131 +0x1055
remote: github.com/codegangsta/cli.(*App).Run(0xc8202678c0, 0xc82000a120, 0x6, 0x6, 0x0, 0x0)
remote:         /home/git/gopath/src/github.com/codegangsta/cli/app.go:175 +0xfd6
remote: main.main()
remote:         /home/git/gopath/src/github.com/gogits/gogs/gogs.go:40 +0x35c
remote:
remote: goroutine 17 [syscall, locked to thread]:
remote: runtime.goexit()
remote:         /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
remote:
remote: goroutine 9 [select]:
remote: github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc820013f80)
remote:         /home/git/gopath/src/github.com/gogits/gogs/modules/log/log.go:236 +0x3cf
remote: created by github.com/gogits/gogs/modules/log.newLogger
remote:         /home/git/gopath/src/github.com/gogits/gogs/modules/log/log.go:162 +0x138
remote: error: hook declined to update refs/heads/master
To https://try.gogs.io/mbentley/docker-demo.git
 ! [remote rejected] master -> master (hook declined)
error: failed to push some refs to 'https://try.gogs.io/mbentley/docker-demo.git'
```

You can test this by cloning this repo, https://github.com/mbentley/docker-demo, and then adding a remote and then try to push to Gogs.  I am now getting error 500s for the repository and I can't delete it.

As a test, I tried to clone the repo from GitHub (which was successful) and then tried to push a new branch and I get the same type of panic.

edit: sorry, I should have included my environment information.  I'm running inside of a Docker container on Ubuntu 14.04, `Gogs version 0.8.37.0215`.  built in sqlite3 db

**Comment by Vorlif** [comment]
The same error here.
Go version: 1.5.3
Gogs version: 0.8.37.0215

**Comment by mbentley** [comment]
I just tested using the `gogs/gogs:0.8.25` docker image and it works as expected for me.

**Comment by Unknwon** [comment]
Thanks your feedback!

I just pushed a fix to `master` and you can test on https://try.gogs.io as well.

**Comment by Vorlif** [comment]
Gogs version: 0.8.37.021**7**
Works for me!

Thanks for your work. Gogs is a very cool project!

**Comment by Unknwon** [comment]
Close as fixed.
