### ISSUE TITLE
Error on push when closing issue from commit message

### ISSUE THREAD

**Issue by mexthemax** [gogits/gogs#2697]
When pushing a commit with a commit message that should close an issue (fixes #issue_id) I get the following error (on the client side that performs `git push`):
```
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 660 bytes | 0 bytes/s, done.
Total 6 (delta 2), reused 0 (delta 0)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x54a7e1]

goroutine 1 [running]:
panic(0xef8b80, 0xc82000e0e0)
        /usr/local/src/go/src/runtime/panic.go:464 +0x3e6
github.com/gogits/gogs/models.createComment(0xc820157900, 0xc820229c00, 0xc820088c60, 0xc82025e280, 0x0, 0x0, 0x2, 0x0, 0x0, 0x0, ...)
        /home/git/gopath/src/github.com/gogits/gogs/models/issue.go:1575 +0x1641
github.com/gogits/gogs/models.createStatusComment(0xc820157900, 0xc820229c00, 0xc820088c60, 0xc82025e280, 0x0, 0x0, 0x0)
        /home/git/gopath/src/github.com/gogits/gogs/models/issue.go:1648 +0xc3
github.com/gogits/gogs/models.(*Issue).changeStatus(0xc82025e280, 0xc820157900, 0xc820229c00, 0xc820216001, 0x0, 0x0)
        /home/git/gopath/src/github.com/gogits/gogs/models/issue.go:254 +0x3ce
github.com/gogits/gogs/models.(*Issue).ChangeStatus(0xc82025e280, 0xc820229c00, 0xc82025e201, 0x0, 0x0)
        /home/git/gopath/src/github.com/gogits/gogs/models/issue.go:269 +0xd2
github.com/gogits/gogs/models.updateIssuesCommit(0xc820229c00, 0xc820089e40, 0xc82020b2c0, 0x9, 0xc8202d418a, 0xd, 0xc820264100, 0x8, 0x8, 0x0, ...)
        /home/git/gopath/src/github.com/gogits/gogs/models/action.go:371 +0xecd
github.com/gogits/gogs/models.CommitRepoAction(0xbff, 0xbff, 0xc820197240, 0x9, 0xc82000f340, 0xd, 0x721, 0xc82020b2c0, 0x9, 0xc8202d418a, ...)
        /home/git/gopath/src/github.com/gogits/gogs/models/action.go:461 +0x1ab8
github.com/gogits/gogs/models.PushUpdate(0xc8202a6e60, 0x11, 0xc820199320, 0x28, 0xc8201997d0, 0x28, 0xbff, 0xc820197240, 0x9, 0xc82020b2c0, ...)
        /home/git/gopath/src/github.com/gogits/gogs/models/update.go:164 +0x1604
github.com/gogits/gogs/cmd.handleUpdateTask(0xc82020f0b0, 0x24, 0xc820285c00, 0xc820284200, 0xc8202d418a, 0xd, 0x0)
        /home/git/gopath/src/github.com/gogits/gogs/cmd/serve.go:110 +0x435
github.com/gogits/gogs/cmd.runServ(0xc82029ca00)
        /home/git/gopath/src/github.com/gogits/gogs/cmd/serve.go:278 +0x14f1
github.com/codegangsta/cli.Command.Run(0x1033d68, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1151420, 0x2f, 0x0, ...)
        /home/git/gopath/src/github.com/codegangsta/cli/command.go:174 +0x1399
github.com/codegangsta/cli.(*App).Run(0xc82029c780, 0xc82005a100, 0x4, 0x4, 0x0, 0x0)
        /home/git/gopath/src/github.com/codegangsta/cli/app.go:187 +0x112b
main.main()
        /home/git/gopath/src/github.com/gogits/gogs/gogs.go:40 +0x368
To git@trygogsio:mexthemax/TestRepoForMe.git
   0ebc4f8..a8947e2  master -> master
error: failed to push some refs to 'git@trygogsio:mexthemax/TestRepoForMe.git'
```

This happens on Version 0.8.43.0223 when pushing to try.gogs.io

The push finishes successfully (commits show up in gogs) and gogs references the commit in the issue but doesn't close the issue.

**Comment by Unknwon** [comment]
Thanks your report!

I just pushed a fix to `develop` branch and updated https://try.gogs.io. 

Please help test again!

**Comment by mexthemax** [comment]
I tested it on https://try.gogs.io and on my own instance and it works again.

Thanks a lot!

**Comment by Unknwon** [comment]
Thanks your confirmation!
