### ISSUE TITLE
gogs start wihout http in docker

### ISSUE THREAD

**Issue by unclegaara** [gogits/gogs#2847]
For bug reports, please give the relevant info:

- Gogs version (or commit ref): 0.9.9.0313
- Git version: 2.6.4
- Operating system: docker gogs/gogs
- Database:
    - [ ] MySQL
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Not relevant
- Log gist:

## Description

Hello, i'm added smtp settings at app.ini then rerun container with gogs, but container was started without http server.
Listened ports in container:
```
bash-4.3# netstat -l  
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN      
tcp        0      0 :::ssh                  :::*                    LISTEN      
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node Path
bash-4.3# 
```
gogs log:
```
bash-4.3# tail -30 log/gogs.log
2016/03/17 04:44:10 [I] Log Mode: File(Trace)
2016/03/17 04:44:10 [I] Cache Service Enabled
2016/03/17 04:44:10 [I] Session Service Enabled
2016/03/17 04:44:10 [I] Mail Service Enabled
2016/03/17 04:44:10 [I] Register Mail Service Enabled
2016/03/17 04:44:10 [I] Notify Mail Service Enabled
2016/03/17 04:44:10 [I] Git Version: 2.6.4
2016/03/17 04:44:10 [T] Doing: CheckRepoStats
2016/03/17 04:44:10 [I] SQLite3 Supported
2016/03/17 04:44:10 [I] Run Mode: Production
2016/03/17 04:44:11 [I] Log Mode: File(Trace)
2016/03/17 04:44:11 [I] Cache Service Enabled
2016/03/17 04:44:11 [I] Session Service Enabled
2016/03/17 04:44:11 [I] Mail Service Enabled
2016/03/17 04:44:11 [I] Register Mail Service Enabled
2016/03/17 04:44:11 [I] Notify Mail Service Enabled
2016/03/17 04:44:11 [I] Git Version: 2.6.4
2016/03/17 04:44:11 [T] Doing: CheckRepoStats
2016/03/17 04:44:11 [I] SQLite3 Supported
2016/03/17 04:44:11 [I] Run Mode: Production
2016/03/17 04:44:12 [I] Log Mode: File(Trace)
2016/03/17 04:44:12 [I] Cache Service Enabled
2016/03/17 04:44:12 [I] Session Service Enabled
2016/03/17 04:44:12 [I] Mail Service Enabled
2016/03/17 04:44:12 [I] Register Mail Service Enabled
2016/03/17 04:44:12 [I] Notify Mail Service Enabled
2016/03/17 04:44:12 [I] Git Version: 2.6.4
2016/03/17 04:44:12 [T] Doing: CheckRepoStats
2016/03/17 04:44:12 [I] SQLite3 Supported
2016/03/17 04:44:12 [I] Run Mode: Production
bash-4.3# 
```
I'm tried to start web server manually and got following error:
```
bash-4.3# su git
bash-4.3$ ./gogs web
2016/03/17 04:45:55 [T] Custom path: /data/gogs
2016/03/17 04:45:55 [T] Log path: /app/gogs/log
2016/03/17 04:45:55 [I] Ronin: Go Git Service 0.9.9.0313
2016/03/17 04:45:56 [I] Log Mode: File(Trace)
2016/03/17 04:45:56 [I] Cache Service Enabled
2016/03/17 04:45:56 [I] Session Service Enabled
2016/03/17 04:45:56 [I] Mail Service Enabled
2016/03/17 04:45:56 [I] Register Mail Service Enabled
2016/03/17 04:45:56 [I] Notify Mail Service Enabled
2016/03/17 04:45:56 [I] Git Version: 2.6.4
2016/03/17 04:45:56 [T] Doing: CheckRepoStats
2016/03/17 04:45:56 [I] SQLite3 Supported
2016/03/17 04:45:56 [I] Run Mode: Production
panic: template: base/head:17: function "CdnMode" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0x7f4deb181028, 0xc822af5bc0, 0x0)
	/usr/lib/go/src/html/template/template.go:330 +0x4b
gopkg.in/macaron%2ev1.compile(0xc8229ee8a0, 0x13, 0xc8229edd20, 0x1, 0x1, 0x0, 0x0, 0xc8229ee900, 0x2, 0x2, ...)
	/tmp/go/src/gopkg.in/macaron.v1/render.go:281 +0x97e
gopkg.in/macaron%2ev1.(*templateSet).Set(0xc8229c8c30, 0x10a3688, 0x7, 0xc8229152c0, 0x0)
	/tmp/go/src/gopkg.in/macaron.v1/render.go:306 +0x4d
gopkg.in/macaron%2ev1.renderHandler(0xc8229ee8a0, 0x13, 0xc8229edd20, 0x1, 0x1, 0x0, 0x0, 0xc8229ee900, 0x2, 0x2, ...)
	/tmp/go/src/gopkg.in/macaron.v1/render.go:373 +0x217
gopkg.in/macaron%2ev1.Renderer(0xc82017cbf8, 0x1, 0x1, 0x0, 0x0)
	/tmp/go/src/gopkg.in/macaron.v1/render.go:410 +0x1ee
github.com/gogits/gogs/cmd.newMacaron(0xc820274780)
	/tmp/go/src/github.com/gogits/gogs/cmd/web.go:131 +0x892
github.com/gogits/gogs/cmd.runWeb(0xc820274780)
	/tmp/go/src/github.com/gogits/gogs/cmd/web.go:185 +0xc2
github.com/codegangsta/cli.Command.Run(0x10af998, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1149360, 0x15, 0x0, ...)
	/tmp/go/src/github.com/codegangsta/cli/command.go:174 +0x1397
github.com/codegangsta/cli.(*App).Run(0xc820274500, 0xc82000a080, 0x2, 0x2, 0x0, 0x0)
	/tmp/go/src/github.com/codegangsta/cli/app.go:187 +0x1135
main.main()
	/tmp/go/src/github.com/gogits/gogs/gogs.go:40 +0x368

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 19 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
	/tmp/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:186 +0x94
created by github.com/gogits/gogs/modules/mailer.NewContext
	/tmp/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:208 +0x7f

goroutine 55 [runnable]:
text/template/parse.lexText(0xc822ad9000, 0x127dd40)
	/usr/lib/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc822ad9000)
	/usr/lib/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/lib/go/src/text/template/parse/lex.go:199 +0x15d

goroutine 9 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc820126480)
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:236 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:162 +0x138

goroutine 11 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc8202a8fc0)
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:236 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:162 +0x138

goroutine 43 [runnable]:
text/template/parse.lexText(0xc822b50900, 0x127dd40)
	/usr/lib/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc822b50900)
	/usr/lib/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/lib/go/src/text/template/parse/lex.go:199 +0x15d

goroutine 29 [chan receive]:
database/sql.(*DB).connectionOpener(0xc820249cc0)
	/usr/lib/go/src/database/sql/sql.go:634 +0x45
created by database/sql.Open
	/usr/lib/go/src/database/sql/sql.go:481 +0x336

goroutine 31 [select]:
github.com/gogits/cron.(*Cron).run(0xc8201f3d00)
	/tmp/go/src/github.com/gogits/cron/cron.go:158 +0x9e8
created by github.com/gogits/cron.(*Cron).Start
	/tmp/go/src/github.com/gogits/cron/cron.go:133 +0x40

goroutine 32 [chan receive]:
github.com/gogits/gogs/models.DeliverHooks()
	/tmp/go/src/github.com/gogits/gogs/models/webhook.go:617 +0x465
created by github.com/gogits/gogs/models.InitDeliverHooks
	/tmp/go/src/github.com/gogits/gogs/models/webhook.go:637 +0x2b

goroutine 33 [chan receive]:
github.com/gogits/gogs/models.TestPullRequests()
	/tmp/go/src/github.com/gogits/gogs/models/pull.go:621 +0x1de
created by github.com/gogits/gogs/models.InitTestPullRequests
	/tmp/go/src/github.com/gogits/gogs/models/pull.go:639 +0x2b

goroutine 34 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc8202a84c0)
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:236 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:162 +0x138

goroutine 56 [runnable]:
text/template/parse.lexText(0xc822ad9100, 0x127dd40)
	/usr/lib/go/src/text/template/parse/lex.go:237 +0x37e
text/template/parse.(*lexer).run(0xc822ad9100)
	/usr/lib/go/src/text/template/parse/lex.go:206 +0x52
created by text/template/parse.lex
	/usr/lib/go/src/text/template/parse/lex.go:199 +0x15d
bash-4.3$ 
```
My app.ini:
```
APP_NAME = Go Git Service
RUN_USER = git
RUN_MODE = prod

[server]
DOMAIN = mydomain.org
PROTOCOL = http
HTTP_PORT = 3000
ROOT_URL = http://mydomain.org/
DISABLE_SSH = false
SSH_PORT = 22
OFFLINE_MODE = false

[database]
DB_TYPE = mysql
HOST = 172.17.42.1:3306
NAME = gogs
USER = root
PASSWD = mypassword
SSL_MODE = disable
PATH = data/gogs.db

[repository]
ROOT = /home/git/gogs-repositories

[mailer]
ENABLED = true
HOST = smtp.yandex.ru:587
FROM = gogs@mydomain.org
USER = gogs@mydomain.org
PASSWD = smtppass

[service]
REGISTER_EMAIL_CONFIRM = true
ENABLE_NOTIFY_MAIL = true
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = true

[session]
PROVIDER = file

[log]
MODE = file
LEVEL = Trace

[security]
INSTALL_LOCK = true
SECRET_KEY = very_secret_key

```

Please help me with this problem!

**Comment by Unknwon** [comment]
You somehow used outdated version of `templates` directory, try to backup your current data, delete container and fetch again.

Close by

> We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io
