### ISSUE TITLE
built-in ssh server panics

### ISSUE THREAD

**Issue by ibotty** [gogits/gogs#2936]
For bug reports, please give the relevant info:

- Gogs version (or commit ref):
  v0.9.13 as well as 5ec8ef023057c8250ae9fab6a2fa26951eec848b (HEAD as of 2016-04-06).

- Git version:
  git version 2.5.5

- Operating system: 
  Linux CentOS via docker base image alpine:3.3 (see https://github.com/ibotty/gogs-openshift)

- Database:
  - [x] SQLite

- Log gist:
```
2016/04/06 07:38:51 [T] Custom path: /data/gogs
2016/04/06 07:38:51 [T] Log path: /app/gogs/log
2016/04/06 07:38:51 [I] Gogs: Go Git Service 0.9.15.0323
2016/04/06 07:38:51 [I] Log Mode: Console(Info)
2016/04/06 07:38:51 [I] Cache Service Enabled
2016/04/06 07:38:51 [I] Session Service Enabled
2016/04/06 07:38:51 [I] SQLite3 Supported
2016/04/06 07:38:51 [I] Run Mode: Production
2016/04/06 07:38:51 [I] SSH server started on :2222
2016/04/06 07:38:52 [I] Listen: http://0.0.0.0:3000
2016/04/06 07:39:04 [T] SSH: Handshaking for 10.1.1.1:41075
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x7b85c7]

goroutine 26 [running]:
github.com/go-xorm/xorm.(*Statement).Where(0xc820b36518, 0x10cee00, 0xe, 0xc820d6ea30, 0x1, 0x1, 0xc820b36500)
	/tmp/go/src/github.com/go-xorm/xorm/statement.go:155 +0x247
github.com/go-xorm/xorm.(*Session).Where(0xc820b36500, 0x10cee00, 0xe, 0xc820d6ea30, 0x1, 0x1, 0xc820bb9380)
	/tmp/go/src/github.com/go-xorm/xorm/session.go:124 +0x5f
github.com/go-xorm/xorm.(*Engine).Where(0x0, 0x10cee00, 0xe, 0xc820d6ea30, 0x1, 0x1, 0x2d5)
	/tmp/go/src/github.com/go-xorm/xorm/engine.go:652 +0x6f
github.com/gogits/gogs/models.SearchPublicKeyByContent(0xc820918000, 0x2d4, 0xc820918000, 0x0, 0x0)
	/tmp/go/src/github.com/gogits/gogs/models/ssh_key.go:447 +0x170
github.com/gogits/gogs/modules/ssh.Listen.func1(0x7f7d81ae9008, 0xc820cbc180, 0x7f7d81adaf28, 0xc820d6e990, 0x217, 0x0, 0x0)
	/tmp/go/src/github.com/gogits/gogs/modules/ssh/ssh.go:154 +0xd5
golang.org/x/crypto/ssh.(*connection).serverAuthenticate(0xc820cbc180, 0xc8209f8370, 0x11, 0x0, 0x0)
	/tmp/go/src/golang.org/x/crypto/ssh/server.go:355 +0x1a74
golang.org/x/crypto/ssh.(*connection).serverHandshake(0xc820cbc180, 0xc8209f8370, 0xc8201c5b80, 0x0, 0x0)
	/tmp/go/src/golang.org/x/crypto/ssh/server.go:223 +0xbbc
golang.org/x/crypto/ssh.NewServerConn(0x7f7d81ae8d58, 0xc82057bb88, 0xc8201c5b80, 0x1, 0x1, 0xc82016a420, 0x0, 0x0)
	/tmp/go/src/golang.org/x/crypto/ssh/server.go:148 +0xe9
github.com/gogits/gogs/modules/ssh.listen.func1(0x7f7d81ae8d58, 0xc82057bb88, 0xc8201c5b80)
	/tmp/go/src/github.com/gogits/gogs/modules/ssh/ssh.go:132 +0x149
created by github.com/gogits/gogs/modules/ssh.listen
	/tmp/go/src/github.com/gogits/gogs/modules/ssh/ssh.go:146 +0x2c0

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f7d81a91f40, 0x72, 0xc820016150)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820d8a060, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820d8a060, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc820d8a000, 0x0, 0x7f7d81a920c0, 0xc82000b320)
	/usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82057bb38, 0xc8205e69a0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82057bb38, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820d848a0, 0x7f7d81ae8d20, 0xc82057bb38, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820d848a0, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc820d80b20, 0xc, 0x7f7d81ae8cf8, 0xc820328300, 0x0, 0x0)
	/usr/lib/go/src/net/http/server.go:1967 +0x8f
github.com/gogits/gogs/cmd.runWeb(0xc8202ae640)
	/tmp/go/src/github.com/gogits/gogs/cmd/web.go:575 +0x21e0
github.com/codegangsta/cli.Command.Run(0x10b5428, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x114f3a0, 0x15, 0x0, ...)
	/tmp/go/src/github.com/codegangsta/cli/command.go:179 +0x1397
github.com/codegangsta/cli.(*App).Run(0xc8200834a0, 0xc82000ad20, 0x2, 0x2, 0x0, 0x0)
	/tmp/go/src/github.com/codegangsta/cli/app.go:196 +0x1386
main.main()
	/tmp/go/src/github.com/gogits/gogs/gogs.go:40 +0x368

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 9 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc82012eac0)
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:236 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:162 +0x138

goroutine 11 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc8202ee3c0)
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:236 +0x3cf
created by github.com/gogits/gogs/modules/log.newLogger
	/tmp/go/src/github.com/gogits/gogs/modules/log/log.go:162 +0x138

goroutine 12 [IO wait]:
net.runtime_pollWait(0x7f7d81a92000, 0x72, 0xc820016150)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82034e060, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82034e060, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82034e000, 0x0, 0x7f7d81a920c0, 0xc82000bb00)
	/usr/lib/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc820352000, 0xc820340ed8, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc820352000, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/tcpsock_posix.go:264 +0x3d
github.com/gogits/gogs/modules/ssh.listen(0xc8201c5b80, 0x8ae)
	/tmp/go/src/github.com/gogits/gogs/modules/ssh/ssh.go:120 +0x16f
created by github.com/gogits/gogs/modules/ssh.Listen
	/tmp/go/src/github.com/gogits/gogs/modules/ssh/ssh.go:183 +0x717

goroutine 27 [IO wait]:
net.runtime_pollWait(0x7f7d81a91e80, 0x72, 0xc820016150)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820cb4060, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820cb4060, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc820cb4000, 0xc820230000, 0x1000, 0x1000, 0x0, 0x7f7d81ad1050, 0xc820016150)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc82057bb88, 0xc820230000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc820d72480)
	/usr/lib/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Read(0xc820d72480, 0xc82061a520, 0x5, 0x5, 0x20, 0x0, 0x0)
	/usr/lib/go/src/bufio/bufio.go:207 +0x260
io.ReadAtLeast(0x7f7d81ae8fe0, 0xc820d72480, 0xc82061a520, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:298 +0xe6
io.ReadFull(0x7f7d81ae8fe0, 0xc820d72480, 0xc82061a520, 0x5, 0x5, 0xc820b36000, 0x0, 0x0)
	/usr/lib/go/src/io/io.go:316 +0x62
golang.org/x/crypto/ssh.(*streamPacketCipher).readPacket(0xc82061a500, 0xc800000006, 0x7f7d81ae8fe0, 0xc820d72480, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/golang.org/x/crypto/ssh/cipher.go:145 +0xc1
golang.org/x/crypto/ssh.(*connectionState).readPacket(0xc820c30000, 0xc820d72480, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/golang.org/x/crypto/ssh/transport.go:111 +0xce
golang.org/x/crypto/ssh.(*transport).readPacket(0xc820c30000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/golang.org/x/crypto/ssh/transport.go:107 +0x55
golang.org/x/crypto/ssh.(*handshakeTransport).readOnePacket(0xc820c30120, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/go/src/golang.org/x/crypto/ssh/handshake.go:173 +0xe7
golang.org/x/crypto/ssh.(*handshakeTransport).readLoop(0xc820c30120)
	/tmp/go/src/golang.org/x/crypto/ssh/handshake.go:145 +0x25
created by golang.org/x/crypto/ssh.newServerTransport
	/tmp/go/src/golang.org/x/crypto/ssh/handshake.go:120 +0x2e2
```

**Comment by ibotty** [comment]
That was a corrupted sqlite database. I did not expect that though.
