### ISSUE TITLE
Push panic to organizational repository

### ISSUE THREAD

**Issue by rbukovansky** [gogits/gogs#4206]
- Gogs version (or commit ref): 0.10.1.0228 `193cc3ba9a831e677ee45d8c1e5c4fd6f29236a3`
- Git version: 2.9.3
- Operating system: Fedora 25
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/TestRBukovansky/TestREPO
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description

When I commit new changes to local repo and then push them to my personal repo on Gogs, it's OK, but when I try to push them to org repo I get this error:

```
remote: panic: runtime error: invalid memory address or nil pointer dereference
remote: [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x5bc5e8]
remote:
remote: goroutine 1 [running]:
remote: panic(0xd3e540, 0xc4200100a0)
remote: 	/home/git/local/go/src/runtime/panic.go:500 +0x1a1
remote: github.com/gogits/gogs/models.prepareHookTasks(0x1393400, 0xc420117900, 0xc4201bfa00, 0xe123be, 0x4, 0x1383b00, 0xc420228700, 0xc42019d2c0, 0x3, 0x5, ...)
remote: 	/home/git/go/src/github.com/gogits/gogs/models/webhook.go:492 +0x998
remote: github.com/gogits/gogs/models.prepareWebhooks(0x1393400, 0xc420117900, 0xc4201bfa00, 0xe123be, 0x4, 0x1383b00, 0xc420228700, 0xcf8301, 0xc420228700)
remote: 	/home/git/go/src/github.com/gogits/gogs/models/webhook.go:564 +0x26c
remote: github.com/gogits/gogs/models.PrepareWebhooks(0xc4201bfa00, 0xe123be, 0x4, 0x1383b00, 0xc420228700, 0x1, 0x82)
remote: 	/home/git/go/src/github.com/gogits/gogs/models/webhook.go:569 +0x6f
remote: github.com/gogits/gogs/models.CommitRepoAction(0xc420016034, 0xb, 0x3, 0xc4201fcde8, 0x8, 0xc420288d20, 0x11, 0xc420082f90, 0x28, 0xc420082fc0, ...)
remote: 	/home/git/go/src/github.com/gogits/gogs/models/action.go:557 +0x76c
remote: github.com/gogits/gogs/models.PushUpdate(0xc420082f90, 0x28, 0xc420082fc0, 0x28, 0xc420288d20, 0x11, 0x1, 0xc420016034, 0xb, 0xc420016015, ...)
remote: 	/home/git/go/src/github.com/gogits/gogs/models/update.go:134 +0x6b7
remote: github.com/gogits/gogs/cmd.runHookPostReceive(0xc42000e780, 0x0, 0xc42000e780)
remote: 	/home/git/go/src/github.com/gogits/gogs/cmd/hook.go:204 +0x4fd
remote: github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xd13260, 0xeb5f48, 0xc42000e780, 0xc420013100, 0x0)
remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0xb9
remote: github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xe1f57e, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe3751b, 0x1e, 0x0, ...)
remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb96
remote: github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4200b9ba0, 0xc42000e500, 0x0, 0x0)
remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:374 +0xb1a
remote: github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.startApp(0xe1219e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe441d3, 0x2c, 0x0, ...)
remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:280 +0x82c
remote: github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xe1219e, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xe441d3, 0x2c, 0x0, ...)
remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:79 +0x16a5
remote: github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc4200b9a00, 0xc42000c200, 0x4, 0x4, 0x0, 0x0)
remote: 	/home/git/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x812
remote: main.main()
remote: 	/home/git/go/src/github.com/gogits/gogs/gogs.go:41 +0x3b5
```

**Comment by Jannik8500** [comment]
If I try to edit a file online (as example the readme file), I get a white screen after saving the change as commit.

This does only happen in orgs.

I think it could be the same bug.

Tested on try.gogs.io with Firefox on windows and Safari on iPhone.

**Comment by Unknwon** [comment]
I can't reproduce locally... what is special about this repository?

**Comment by Unknwon** [comment]
OK, this is not a problem in `master`, or `0.10.1` release binary. But only happens in `develop`. So you just want to upgrade to 0.10.1/master, it is fine.

**Comment by rbukovansky** [comment]
Well, I have always run `develop` version and it was always fine... Just not now...

**Comment by Unknwon** [comment]
@rbukovansky the code is merged from another unstable branch, like few hours ago.

**Comment by Unknwon** [comment]
It is now fixed in `develop` branch.

**Comment by rbukovansky** [comment]
Yup, problem seems to be solved. Thanks for quick response!
