### ISSUE TITLE
Restore fails with sqlite and docker

### ISSUE THREAD

**Issue by LukeMauldin** [gogits/gogs#4418]
- Gogs version (or commit ref): 0.11.4 (Docker image cd36c8b94b34 pulled on 4/11/2017)
- Operating system: Suse Leap 42.2
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [ X] SQLite

Ran `gogs backup` to backup to a archive file.  Started docker container gogs:0.11.4, ran `docker exec` into gogs container and attempted to do a `gogs restore` from the backup archive.  Received the following panic:
```
bash-4.3$ /app/gogs/gogs restore -v --from /data/gogs-backup-1491891895.zip
2017/04/11 06:46:55 [ INFO] Restore backup from: /data/gogs-backup-1491891895.zip
Unzipping /data/gogs-backup-1491891895.zip...
Extracting file...gogs-backup/
Extracting file...gogs-backup/metadata.ini
Extracting file...gogs-backup/db/
Extracting file...gogs-backup/db/User.json
Extracting file...gogs-backup/db/PublicKey.json
Extracting file...gogs-backup/db/AccessToken.json
Extracting file...gogs-backup/db/Repository.json
Extracting file...gogs-backup/db/DeployKey.json
Extracting file...gogs-backup/db/Collaboration.json
Extracting file...gogs-backup/db/Access.json
Extracting file...gogs-backup/db/Upload.json
Extracting file...gogs-backup/db/Watch.json
Extracting file...gogs-backup/db/Star.json
Extracting file...gogs-backup/db/Follow.json
Extracting file...gogs-backup/db/Action.json
Extracting file...gogs-backup/db/Issue.json
Extracting file...gogs-backup/db/PullRequest.json
Extracting file...gogs-backup/db/Comment.json
Extracting file...gogs-backup/db/Attachment.json
Extracting file...gogs-backup/db/IssueUser.json
Extracting file...gogs-backup/db/Label.json
Extracting file...gogs-backup/db/IssueLabel.json
Extracting file...gogs-backup/db/Milestone.json
Extracting file...gogs-backup/db/Mirror.json
Extracting file...gogs-backup/db/Release.json
Extracting file...gogs-backup/db/LoginSource.json
Extracting file...gogs-backup/db/Webhook.json
Extracting file...gogs-backup/db/HookTask.json
Extracting file...gogs-backup/db/ProtectBranch.json
Extracting file...gogs-backup/db/ProtectBranchWhitelist.json
Extracting file...gogs-backup/db/Team.json
Extracting file...gogs-backup/db/OrgUser.json
Extracting file...gogs-backup/db/TeamUser.json
Extracting file...gogs-backup/db/TeamRepo.json
Extracting file...gogs-backup/db/Notice.json
Extracting file...gogs-backup/db/EmailAddress.json
Extracting file...gogs-backup/db/Version.json
Extracting file...gogs-backup/custom/
Extracting file...gogs-backup/custom/conf/
Extracting file...gogs-backup/custom/conf/app.ini
Extracting file...gogs-backup/data/
Extracting file...gogs-backup/data/avatars/
Extracting file...gogs-backup/data/avatars/1
Extracting file...gogs-backup/data/avatars/23
Extracting file...gogs-backup/data/avatars/33
Extracting file...gogs-backup/data/avatars/38
Extracting file...gogs-backup/data/avatars/41
Extracting file...gogs-backup/data/avatars/15
Extracting file...gogs-backup/data/avatars/16
Extracting file...gogs-backup/data/avatars/34
Extracting file...gogs-backup/data/avatars/35
Extracting file...gogs-backup/data/avatars/37
Extracting file...gogs-backup/data/avatars/40
Extracting file...gogs-backup/data/avatars/32
Extracting file...gogs-backup/data/avatars/36
Extracting file...gogs-backup/data/avatars/4
Extracting file...gogs-backup/data/avatars/14
Extracting file...gogs-backup/data/avatars/43
Extracting file...gogs-backup/data/avatars/13
Extracting file...gogs-backup/data/avatars/5
Extracting file...gogs-backup/data/avatars/9
Extracting file...gogs-backup/data/avatars/10
Extracting file...gogs-backup/repositories.zip
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x809d2d]

goroutine 1 [running]:
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Session).Begin(0xc420088500, 0xf8d8b0, 0xc420088500)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/session_tx.go:10 +0x10d
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Engine).DropTables(0x0, 0xc420097468, 0x1, 0x1, 0x0, 0x0)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/engine.go:1394 +0x84
github.com/gogits/gogs/models.ImportDatabase(0xc420409e00, 0x13, 0x2, 0xc420409e00)
        /tmp/go/src/github.com/gogits/gogs/models/models.go:315 +0x35c
github.com/gogits/gogs/cmd.runRestore(0xc4203ec780, 0x100, 0xc4203ec780)
        /tmp/go/src/github.com/gogits/gogs/cmd/restore.go:86 +0x780
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xe2e6c0, 0xf8c258, 0xc4203ec780, 0xc4203c4e00, 0x0)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0xb9
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xf4b417, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf75366, 0x26, 0x0, ...)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc4203f8340, 0xc4200100f0, 0x5, 0x5, 0x0, 0x0)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
        /tmp/go/src/github.com/gogits/gogs/gogs.go:41 +0x3ea
bash-4.3$ /app/gogs/
```

**Comment by Unknwon** [comment]
Hi, is this still happening in the current `latest` tag of Docker image?

**Comment by LukeMauldin** [comment]
Yes

**Comment by Unknwon** [comment]
I suspect you're not running the latest version, because line `models/models.go:315` is a bracket.

**Comment by LukeMauldin** [comment]
OK, I will try to update again and let you know
