### ISSUE TITLE
golang 1.8.1 xorm error

### ISSUE THREAD

**Issue by ddatsh** [gogits/gogs#4449]
golang version:1.8.1
Gogs version (or commit ref): 6500aafc
Operating system:win10 x64
Database (use [x]):
[X] Not relevant

git clone 
Cloning into 'xx'...
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x50 pc=0x7bddc8]

goroutine 1 [running]:
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Engine).autoMapType(0x0, 0xebb060, 0xc042214200, 0x199, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/engine.go:779 +0x78
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Statement).setRefValue(0xc04225a298, 0xebb060, 0xc042214200, 0x199)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/statement.go:219 +0x7a
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Session).Get(0xc04225a280, 0xebb8e0, 0xc042214200, 0x200, 0x0, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/session_get.go:23 +0xf3
github.com/gogits/gogs/vendor/github.com/go-xorm/xorm.(*Engine).Get(0x0, 0xebb8e0, 0xc042214200, 0x0, 0x0, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/go-xorm/xorm/engine.go:1467 +0x9a
github.com/gogits/gogs/models.GetUserByName(0xc04206f841, 0x6, 0xec8759, 0x4, 0x1)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/models/user.go:928 +0xc5
github.com/gogits/gogs/cmd.runServ(0xc042178280, 0x0, 0xc042178280)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/cmd/serv.go:155 +0x2c2
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xdaefa0, 0xf10850, 0xc042178280, 0xc042034600, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0xc0
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xec9401, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf004e7, 0x2f, 0x0, ...)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb79
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc042032ea0, 0xc04203e100, 0x4, 0x4, 0x0, 0x0)
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x7d7
main.main()
        d:/workspaces/go/gogs/src/github.com/gogits/gogs/gogs.go:41 +0x3f1
fatal: Could not read from remote repository.
```

golang 1.8.0/1.7.5 no problem

**Comment by ddatsh** [comment]
golang 1.8.1 升到xorm的最新版再编译就好了0.6.2.0412
