### ISSUE TITLE
gogs，eclipse git push出现401 Unauthorized（急）

### ISSUE THREAD

**Issue by gyjx** [gogits/gogs#4466]
gogs开发团队你们好，

我在用eclipse的git插件push的时候出现以下问题，
Can't connect to any repository: http://192.168.133.133:3000/tuan/ihome.git (http://192.168.133.133:3000/tuan/ihome.git: 401 Unauthorized)

使用Git Bash -》执行 git push origin master 是可以正常push

开始我怀疑是，我的eclipse git插件出现问题,紧接着我切换到github，gitosc，push都是正常！

Eclipse版本
Luna Service Release 1a (4.4.1),32位

所以我想请问gogs开发者，是否运到这个问题？

在搭建gogs的配置

[root@localhost gogs]# less custom/conf/app.ini 
APP_NAME = Gogs
RUN_USER = root
RUN_MODE = prod

[database]
DB_TYPE  = mysql
HOST     = 192.168.133.133:3306
NAME     = gogs
USER     = root
PASSWD   = root
SSL_MODE = disable
PATH     = data/gogs.db

[repository]
ROOT = /git/gogs-repositories

[server]
DOMAIN           = 192.168.133.133
HTTP_PORT        = 3000
ROOT_URL         = http://192.168.133.133:3000/
DISABLE_SSH      = false
SSH_PORT         = 22
START_SSH_SERVER = false
OFFLINE_MODE     = false

[mailer]
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = false
ENABLE_CAPTCHA         = true
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[session]
PROVIDER = file

[log]
MODE      = console, file
LEVEL     = Info
ROOT_PATH = /git/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = 8MyRxC5oi20eDoo

(END) 
ENABLED = false

[service]
REGISTER_EMAIL_CONFIRM = false
ENABLE_NOTIFY_MAIL     = false
DISABLE_REGISTRATION   = false
ENABLE_CAPTCHA         = true
REQUIRE_SIGNIN_VIEW    = false

[picture]
DISABLE_GRAVATAR        = false
ENABLE_FEDERATED_AVATAR = true

[session]
PROVIDER = file

[log]
MODE      = console, file
LEVEL     = Info
ROOT_PATH = /git/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = 8MyRxC5oi20eDoo

**Comment by ruanjingwang** [comment]
出现同样的问题
日志如下：
Exception in thread "main" org.eclipse.jgit.api.errors.TransportException: http://run@10.1.1.20:10080/run/test.git: 401 Unauthorized
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:164)
	at com.run.util.GitUtils.main(GitUtils.java:489)
Caused by: org.eclipse.jgit.errors.TransportException: http://run@10.1.1.20:10080/run/test.git: 401 Unauthorized
	at org.eclipse.jgit.transport.TransportHttp$Service.openResponse(TransportHttp.java:875)
	at org.eclipse.jgit.transport.TransportHttp$MultiRequestService.execute(TransportHttp.java:977)
	at org.eclipse.jgit.transport.TransportHttp$Service$HttpExecuteStream.read(TransportHttp.java:903)
	at org.eclipse.jgit.util.io.UnionInputStream.read(UnionInputStream.java:145)
	at org.eclipse.jgit.util.IO.readFully(IO.java:247)
	at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:186)
	at org.eclipse.jgit.transport.SideBandInputStream.needDataPacket(SideBandInputStream.java:154)
	at org.eclipse.jgit.transport.SideBandInputStream.read(SideBandInputStream.java:136)
	at org.eclipse.jgit.util.IO.readFully(IO.java:247)
	at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:186)
	at org.eclipse.jgit.transport.PacketLineIn.readString(PacketLineIn.java:138)
	at org.eclipse.jgit.transport.BasePackPushConnection.readStringLongTimeout(BasePackPushConnection.java:375)
	at org.eclipse.jgit.transport.BasePackPushConnection.readStatusReport(BasePackPushConnection.java:327)
	at org.eclipse.jgit.transport.BasePackPushConnection.doPush(BasePackPushConnection.java:202)
	at org.eclipse.jgit.transport.TransportHttp$SmartHttpPushConnection.doPush(TransportHttp.java:807)
	at org.eclipse.jgit.transport.BasePackPushConnection.push(BasePackPushConnection.java:154)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:167)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1250)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:157)
	... 1 more

**Comment by ruanjingwang** [comment]
0.11.4 和0.11.6 都有同样的bug。

**Comment by Eng3l** [comment]
Having the same issue with netbeans, but when I push trough terminal works OK.

**Comment by Unknwon** [comment]
Can you reproduce on demo site?

**Comment by gyjx** [comment]
What do I need to do?

**Comment by Unknwon** [comment]
Can you reproduce this issue on demo site?

**Comment by gyjx** [comment]
ok,Wait a moment！

**Comment by gyjx** [comment]
日志信息:
[Macaron] 2017-05-18 19:29:34: Started POST /tuan001/ihome.git/git-receive-pack for 192.168.133.1
2017/05/18 19:29:34 [TRACE] Session ID: 372aeef284564946
2017/05/18 19:29:34 [TRACE] CSRF Token: FL01DFJMl9InhjrxWR5cK745jGo6MTQ5NTEwNjk3NDcyMjg5NzY2Mw==
**[Macaron] 2017-05-18 19:29:34: Completed POST /tuan001/ihome.git/git-receive-pack 401** Unauthorized in 15.947562ms
截图如下:
https://github.com/gyjx/test/blob/master/002.png

Eclipse问题如下:
https://github.com/gyjx/test/blob/master/%E6%97%A0%E6%A0%87%E9%A2%98.png

Can't connect to any repository: http://192.168.133.133:3000/tuan001/ihome.git (http://192.168.133.133:3000/tuan001/ihome.git: 401 Unauthorized)

**Comment by gyjx** [comment]
gogs部署在VM虚拟机 centos6.9_64

**Comment by Unknwon** [comment]
Thanks for your time and sorry about inconvenience. 

However:

1. You are not answering my question: Can you reproduce this issue on demo site?
2. Please read issue template, the one you delete without a second thought: https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by strangeryf** [comment]
reproduced in our environment:
Eclipse reported:
Failed pushing to http://blablabla/bla/bla.git
 http://blablabla/bla/bla.git: 401 Unauthorized
gogs web output read:
[Macaron] 2017-05-18 17:41:52: Completed POST /bla/blablabla.git/git-receive-pack 401 Unauthorized in 9.0005ms
gogs version: 0.11.4.0405

**Comment by Unknwon** [comment]
If you can't reproduce on demo site and git bash works fine... I can't help you..

**Comment by gyjx** [comment]
Can't connect to any repository: https://try.gogs.io/xiaoye/test.git (https://try.gogs.io/xiaoye/test.git: 401 Unauthorized)

**Comment by gyjx** [comment]
我在你们demo site 通过eclipse提交代码，也是不行的！

**Comment by Unknwon** [comment]
According to https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md:

>1. Please speak English, we have forum in [Chinese](https://discuss.gogs.io/c/getting-help/getting-help-chinese).

**Comment by gyjx** [comment]
sorry,my English is poor！
I have already posted a question description in your Chinese Forum. Please click on this hyperlink。

https://discuss.gogs.io/t/eclipse-git-https-try-gogs-io-https-try-gogs-io-xiaoye-test-git-401-unauthorized/1138

thank you!

**Comment by lrlovecode** [comment]
@gyjx 请问这个问题解决了吗？能说下解决方案吗

**Comment by gyjx** [comment]
@lrlovecode  sorry!

**Comment by xiaoyi001yeye** [comment]
@lrlovecode  把仓库设置成私有的。Set your warehouse to private.
