### ISSUE TITLE
Eclipse EGIT client fails with 401 error when attempt to push using https

### ISSUE THREAD

**Issue by franTarkenton** [gogits/gogs#4531]
- **GOGS Version:** 0.11.4 
- **Git Version:** Eclipse EGIT, 4.7.0.201704051617-r, issue exists in all versions of egit that I have tried that include the full suite of Neon releases, as well as pre-release of Oxygene
- **Operating system:** Windows 7 SP1, 
- **Database (use `[x]`):**
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [x ] Yes (https://try.gogs.io/KevinTester/TestTest.git)
  - [ ] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
I am using the Eclipse IDE.  Eclipse integrates git operations into the IDE, allowing you to perform most GIT operations directly from the IDE.  When I attempt to push my changes using eclipse (https) to a remote GOGS repo I consistently get a 401 unauthorized error.  

If however I go into GOGS and change the repo so that its a private, and then attempt to push, egit will either request my credentials or it will use the cached credentials and complete the push successfully.  

This issue does not occur with the GIT command line. 

To reproduce issue: 
1. clone the repository: https://try.gogs.io/KevinTester/TestTest.git
2. add the cloned repo to eclipse
3. turn off sslVerify (this could be unique to my environment)
  - git config http.sslVerify false
4. make some changes to the readme file and then commit and push.  You should get a prompt asking for credentials, but instead it will error, with the message: Can't connect to any repository: 401 Unauthorized)

interestingly enough if I toggle the repository to become a private repo, and then retry the push in eclipse everything works correctly, i.e. it gives me a prompt for the credentials, or uses the cached credentials and completes the push successfully.

The issue only seems to come up with GOGS, I don't have this issue when working with other remote git repositories like bitbucket, or github.

Please let me know if I can do anything to help resolve this bug / issue

Thanks.

**Comment by linquize** [comment]
```
$ org.eclipse.jgit.pgm-4.7.0.201704051617-r.sh push
Counting objects:       3
Finding sources:        100% (3/3)
Getting sizes:          100% (2/2)
Compressing objects:    100% (101/101)
Writing objects:        100% (3/3)
org.eclipse.jgit.api.errors.TransportException: https://try.gogs.io/KevinTester/TestTest.git: 401 Unauthorized
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:180)
        at org.eclipse.jgit.pgm.Push.run(Push.java:136)
        at org.eclipse.jgit.pgm.TextBuiltin.execute(TextBuiltin.java:199)
        at org.eclipse.jgit.pgm.Main.execute(Main.java:252)
        at org.eclipse.jgit.pgm.Main.run(Main.java:143)
        at org.eclipse.jgit.pgm.Main.main(Main.java:115)
Caused by: org.eclipse.jgit.errors.TransportException: https://try.gogs.io/KevinTester/TestTest.git: 401 Unauthorized
        at org.eclipse.jgit.transport.TransportHttp$Service.openResponse(TransportHttp.java:972)
        at org.eclipse.jgit.transport.TransportHttp$MultiRequestService.execute(TransportHttp.java:1076)
        at org.eclipse.jgit.transport.TransportHttp$Service$HttpExecuteStream.read(TransportHttp.java:1001)
        at org.eclipse.jgit.util.io.UnionInputStream.read(UnionInputStream.java:145)
        at org.eclipse.jgit.util.IO.readFully(IO.java:247)
        at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:225)
        at org.eclipse.jgit.transport.SideBandInputStream.needDataPacket(SideBandInputStream.java:154)
        at org.eclipse.jgit.transport.SideBandInputStream.read(SideBandInputStream.java:136)
        at org.eclipse.jgit.util.IO.readFully(IO.java:247)
        at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:225)
        at org.eclipse.jgit.transport.PacketLineIn.readString(PacketLineIn.java:155)
        at org.eclipse.jgit.transport.BasePackPushConnection.readStringLongTimeout(BasePackPushConnection.java:422)
        at org.eclipse.jgit.transport.BasePackPushConnection.readStatusReport(BasePackPushConnection.java:369)
        at org.eclipse.jgit.transport.BasePackPushConnection.doPush(BasePackPushConnection.java:221)
        at org.eclipse.jgit.transport.TransportHttp$SmartHttpPushConnection.doPush(TransportHttp.java:886)
        at org.eclipse.jgit.transport.BasePackPushConnection.push(BasePackPushConnection.java:170)
        at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:172)
        at org.eclipse.jgit.transport.Transport.push(Transport.java:1310)
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:169)
        ... 5 more

```

**Comment by linquize** [comment]
No such problem in gogs v0.8.10

**Comment by linquize** [comment]
No such problem in gogs v0.8.10 - v0.9.141
Problem exists since gogs v0.10(RC)

**Comment by linquize** [comment]
The problem is from commit v0.9.141-51 d521e716dd59617dbbb637a3e8028bf4a5c6f849

**Comment by linquize** [comment]
If you use core git client, you will find git sends objects before promoting username/password. This is very strange.

```
$ git push
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 291 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
Username for 'http://localhost:3000':
```

**Comment by tgreen2** [comment]
Recently upgraded to 0.11.10 and experience the same issue with Eclipse Git in Neon.3 over normal HTTP. If the repository is changed to Private, Eclipse Git will work. Other Git clients appear to work without adjustments. Everything was working correctly with Gogs / Eclipse Git prior to upgrading from 0.8.22.0115.

**Comment by Unknwon** [comment]
Based on https://discuss.gogs.io/t/eclipse-git-https-try-gogs-io-https-try-gogs-io-xiaoye-test-git-401-unauthorized/1138/9, change visibility to private can push normally. But still no idea about the core issue.

**Comment by tomaswolf** [comment]
JGit connects to `https://<gogs-server>/<user>/<repo>.git/info/refs?service=git-receive-pack`. The server does not ask for authentication for this URL if the repo is public, returns HTTP 200 and a meaningful result. When JGit then tries to send data to the git-receive-pack endpoint, the server suddenly responds with the 401.

Don't know if that is correct, or if the server should ask for authentication already for the `service=git-receive-pack` query.

JGit bug is https://bugs.eclipse.org/bugs/show_bug.cgi?id=513043 .

**Comment by tomaswolf** [comment]
Looks to me as if [this change](https://github.com/gogits/gogs/commit/d521e716dd59617dbbb637a3e8028bf4a5c6f849#diff-ccdf93430400107520f30815fe24a649R53) sets `isPull` to true for all GET requests, and then later (line 70) skips authentication if the repo is public.

**Comment by tomaswolf** [comment]
@linquize wrote above:
> If you use core git client, you will find git sends objects before promoting username/password. This is very strange.

No, it isn't. The 401 can be gotten by the client only after it has sent the data. Only then it can re-try, and it must re-send the data.

For JGit, there's a fix in the works, but it'll also have to send the data at least twice.

I think it would be much better if GOGS required authentication already on the capability-checking GET to `info/refs?service=git-receive-pack`. Authentication re-tries will then occur on this cheap request, and the POST can then be done with the correct authentication headers up front, and the client thus needs to send the data only once.

**Comment by tomaswolf** [comment]
JGit has been fixed now to handle servers that request authentication only on the POST. So with an EGit/JGit from the [latest nightly builds](http://download.eclipse.org/egit/updates-nightly), this problem should no longer occur.

It would still be good if GOGS required authentication for receive-pack already on the GET. Authentication on POST only slows down clients in general, not just JGit, since they'll have to send data twice.

**Comment by malm66** [comment]
I have the same (similar) problem with EGit/jGit even after installing the latest version from the nightly build repository. We are connecting to a locally hosted TFS GIT instance using https. Git Windows command line client as well as GUI front ends like SourceTree or the Github Desktop work fine. EGit does prompt for credentials but then fails with an authentication error. Here is a sample stacktrace:

!ENTRY org.eclipse.egit.core 4 0 2017-09-27 15:33:03.493
!MESSAGE An exception occurred during push on URI https://tfs.synergy.net.au/tfs/Synergy/WBU/_git/STARS: https://tfs.synergy.net.au/tfs/Synergy/
WBU/_git/STARS: null
!STACK 0
org.eclipse.jgit.api.errors.TransportException: https://tfs.synergy.net.au/tfs/Synergy/WBU/_git/STARS: null
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:180)
        at org.eclipse.egit.core.op.PushOperation.run(PushOperation.java:215)
        at org.eclipse.egit.ui.internal.push.PushJob.performJob(PushJob.java:84)
        at org.eclipse.egit.ui.internal.jobs.RepositoryJob.run(RepositoryJob.java:57)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.eclipse.jgit.errors.TransportException: https://tfs.synergy.net.au/tfs/Synergy/WBU/_git/STARS: null
        at org.eclipse.jgit.transport.BasePackPushConnection.doPush(BasePackPushConnection.java:238)
        at org.eclipse.jgit.transport.TransportHttp$SmartHttpPushConnection.doPush(TransportHttp.java:1119)
        at org.eclipse.jgit.transport.BasePackPushConnection.push(BasePackPushConnection.java:170)
        at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:172)
        at org.eclipse.jgit.transport.Transport.push(Transport.java:1310)
        at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:169)
        ... 4 more
Caused by: java.io.IOException
        at org.eclipse.jgit.transport.HttpAuthMethod$Negotiate.configureRequest(HttpAuthMethod.java:560)
        at org.eclipse.jgit.transport.TransportHttp.httpOpen(TransportHttp.java:861)
        at org.eclipse.jgit.transport.TransportHttp$Service.openStream(TransportHttp.java:1150)
        at org.eclipse.jgit.transport.TransportHttp$Service.sendRequest(TransportHttp.java:1187)
        at org.eclipse.jgit.transport.TransportHttp$MultiRequestService.execute(TransportHttp.java:1415)
        at org.eclipse.jgit.transport.TransportHttp$Service$HttpExecuteStream.read(TransportHttp.java:1345)
        at org.eclipse.jgit.util.io.UnionInputStream.read(UnionInputStream.java:145)
        at java.io.FilterInputStream.read(FilterInputStream.java:133)
        at org.eclipse.jgit.util.io.TimeoutInputStream.read(TimeoutInputStream.java:112)
        at org.eclipse.jgit.util.IO.readFully(IO.java:247)
        at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:225)
        at org.eclipse.jgit.transport.SideBandInputStream.needDataPacket(SideBandInputStream.java:154)
        at org.eclipse.jgit.transport.SideBandInputStream.read(SideBandInputStream.java:136)
        at org.eclipse.jgit.util.IO.readFully(IO.java:247)
        at org.eclipse.jgit.transport.PacketLineIn.readLength(PacketLineIn.java:225)
        at org.eclipse.jgit.transport.PacketLineIn.readString(PacketLineIn.java:155)
        at org.eclipse.jgit.transport.BasePackPushConnection.readStringLongTimeout(BasePackPushConnection.java:437)
        at org.eclipse.jgit.transport.BasePackPushConnection.readStatusReport(BasePackPushConnection.java:369)
        at org.eclipse.jgit.transport.BasePackPushConnection.doPush(BasePackPushConnection.java:221)
        ... 9 more
Caused by: GSSException: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Attempt to obtain new I
NITIATE credentials failed! (null)))
        at sun.security.jgss.spnego.SpNegoContext.initSecContext(SpNegoContext.java:454)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:248)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
        at org.eclipse.jgit.transport.HttpAuthMethod$Negotiate.configureRequest(HttpAuthMethod.java:554)
        ... 27 more
Caused by: GSSException: No valid credentials provided (Mechanism level: Attempt to obtain new INITIATE credentials failed! (null))
        at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:343)
        at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:145)
        at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
        at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
        at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
        at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
        at sun.security.jgss.spnego.SpNegoContext.GSS_initSecContext(SpNegoContext.java:882)
        at sun.security.jgss.spnego.SpNegoContext.initSecContext(SpNegoContext.java:317)
        ... 30 more
Caused by: javax.security.auth.login.LoginException: No password provided
        at com.sun.security.auth.module.Krb5LoginModule.promptForPass(Krb5LoginModule.java:919)
        at com.sun.security.auth.module.Krb5LoginModule.attemptAuthentication(Krb5LoginModule.java:760)
        at com.sun.security.auth.module.Krb5LoginModule.login(Krb5LoginModule.java:617)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at javax.security.auth.login.LoginContext.invoke(LoginContext.java:755)
        at javax.security.auth.login.LoginContext.access$000(LoginContext.java:195)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:682)
        at javax.security.auth.login.LoginContext$4.run(LoginContext.java:680)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.login.LoginContext.invokePriv(LoginContext.java:680)
        at javax.security.auth.login.LoginContext.login(LoginContext.java:587)
        at sun.security.jgss.GSSUtil.login(GSSUtil.java:258)
        at sun.security.jgss.krb5.Krb5Util.getTicket(Krb5Util.java:158)
        at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:335)
        at sun.security.jgss.krb5.Krb5InitCredential$1.run(Krb5InitCredential.java:331)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.jgss.krb5.Krb5InitCredential.getTgt(Krb5InitCredential.java:330)
        ... 38 more

**Comment by tomaswolf** [comment]
This isn't the same issue. You're trying to connect to a TFS server, not GOGS. Let's continue this discussion in the [Egit forum](https://www.eclipse.org/forums/index.php/t/1089090/), where you already had posted this, but then never replied to my questions.

**Comment by malm66** [comment]
My apologies for being tardy. Different to this forum the Eclipse Egit forum didn't send me a notification when you posted your questions and I failed to check it manually. Anyway, I posted answers to your questions in the Egit forum.

**Comment by maximeozenne** [comment]
I used to set the visibility to private but now I installed Gogs for at my work and we can't work in team if we set the visibility to private... Any other solution ?

**Comment by RoboPhred** [comment]
This issue isn't restricted to this one client.  I see identical behavior with nodegit.
GETs git-receive-pack which returns 200, then chokes on POST git-receive-pack with 401.  Client is capable of asking for credentials, but never does as the GET returns 200.

**Comment by Franselbaer** [comment]
Same here with Git commandline client (git version 1.7.10.4)

**Comment by Franselbaer** [comment]
Seems to be a git client issue with 1.7.10... installed 1.9.1 from Backports and it now asks for credentials for public repo's as well and works successfully.

Seems that "public" repo's could have been pushed with anonymous user earlier e.g. on github.. But with Gogs you need to use your credentials to push in any case. Newer git clients seems to be aware of that.

**Comment by linquize** [comment]
But git 1.7/1.9 is quite old

**Comment by Nackloose** [comment]
This issue seems to have disappeared for me personally with the most recent update.
I can push using netbeans again just fine with making the repository private.

**Comment by steveatlabor** [comment]
I think it worked for you because you made the repository private. I'm still experiencing the issue after updating to the latest version.

**Comment by dfresh613** [comment]
Also encountering this problem. I can confirm that downgrading to 0.9.128.0131 makes this issue go away.

When i attempt to make the same clone in the latest version, i get the initially mentioned failure.

**Comment by thedmo** [comment]
Hey, its 2020 and this issue still seems to be around. 
We're using  2020 Gogs Version: 0.11.91.0811
I use the Github Desktop Client now but did try it with Cong and gitG aswell. after changing the status to private, it just worked ^^"
