### ISSUE TITLE
GOGS not starting

### ISSUE THREAD

**Issue by Fastidious** [gogits/gogs#4618]
- Gogs version (or commit ref): `0.11.19.0609`
- Git version: `2.13.1`
- Operating system: `Ubuntu 17.04`
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`): `See description.`

## Description

Crashing on start. Getting:

```
2017/07/11 11:10:00 [TRACE] Custom path: /opt/gogs/custom
2017/07/11 11:10:00 [TRACE] Log path: /opt/gogs/log
2017/07/11 11:10:00 [TRACE] Log Mode: File (Trace)
2017/07/11 11:10:00 [ INFO] Gogs 0.11.19.0609
panic: template: repo/settings/webhook_list:13: function "AppSubUrl" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0x172d1e0, 0xc4208648a0, 0x0)
        /usr/local/go/src/html/template/template.go:360 +0x54
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.compile(0xc4201bcc40, 0x13, 0xc4201e3060, 0x1, 0x1, 0x0, 0x0, 0xc4201bcca0, 0x2, 0x2, ...)
        /home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:292 +0x4cc
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.(*TemplateSet).Set(0xc4201b8fc0, 0xf714f8, 0x7, 0xc4201ba000, 0x0)
        /home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:318 +0x63
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.renderHandler(0xc4201bcc40, 0x13, 0xc4201e3060, 0x1, 0x1, 0x0, 0x0, 0xc4201bcca0, 0x2, 0x2, ...)
        /home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:385 +0x18d
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.Renderer(0xc42018b1e0, 0x1, 0x1, 0xa, 0x1)
        /home/vagrant/gopath/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:422 +0x172
github.com/gogits/gogs/cmd.newMacaron(0xc4203cb540)
        /home/vagrant/gopath/src/github.com/gogits/gogs/cmd/web.go:110 +0x5cf
github.com/gogits/gogs/cmd.runWeb(0xc4203cb540, 0x0, 0xc4203cb540)
        /home/vagrant/gopath/src/github.com/gogits/gogs/cmd/web.go:166 +0x74
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xe516a0, 0xfb4c58, 0xc4203cb540, 0xc4203bb200, 0x0)
        /home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0xb9
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xf6c9f4, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf80472, 0x10, 0x0, ...)
        /home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc4200f1d40, 0xc42000c140, 0x2, 0x2, 0x0, 0x0)
        /home/vagrant/gopath/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
        /home/vagrant/gopath/src/github.com/gogits/gogs/gogs.go:41 +0x3ea
```

**Comment by Fastidious** [comment]
Found fix, [referred here](https://github.com/gogits/gogs/issues/4585). Upgrade documentation might need to be updated? Leaving this open until @Unknwon sees it.

**Comment by Unknwon** [comment]
@Fastidious upgrade docs asks you to remove old template files first: https://gogs.io/docs/upgrade/upgrade_from_binary
