### ISSUE TITLE
Raspberry pi docker image is broken

### ISSUE THREAD

**Issue by schvabodka-man** [gogits/gogs#4796]
- Gogs version (or commit ref): latest from docker hub
- Git version: irrelevant
- Operating system: Raspbian
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant

## Description
Hello, i'm trying to install gogs on pi 3 using docker `docker run -p 10022:22 -p 10080:3000 -v /home/pi/Data/Git:/data gogs/gogs-rpi`
I'm getting this on server start (when server try to run listeners for http)
`panic: template: admin/auth/edit:15: function "AppSubUrl" not defined`
This thing happens not only with current build but with earlier too

**Comment by schvabodka-man** [comment]
Also, here is some log

```
goroutine 1 [running]:
html/template.Must(0x0, 0xe44198, 0x1169e628, 0x0)
	/usr/local/go/src/html/template/template.go:360 +0x40
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.compile(0x1171f980, 0x13, 0x116b07e8, 0x1, 0x1, 0x0, 0x0, 0x11718eb0, 0x2, 0x2, ...)
	/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:292 +0x3c0
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.(*TemplateSet).Set(0x1171fa00, 0x971d57, 0x7, 0x116b8f80, 0x0)
	/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:318 +0x2c
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.renderHandler(0x1171f980, 0x13, 0x116b07e8, 0x1, 0x1, 0x0, 0x0, 0x11718eb0, 0x2, 0x2, ...)
	/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:385 +0x13c
github.com/gogits/gogs/vendor/gopkg.in/macaron%2ev1.Renderer(0x114e18e8, 0x1, 0x1, 0x1171f9a0, 0x14)
	/tmp/go/src/github.com/gogits/gogs/vendor/gopkg.in/macaron.v1/render.go:422 +0xb0
github.com/gogits/gogs/cmd.newMacaron(0x116c80a0)
	/tmp/go/src/github.com/gogits/gogs/cmd/web.go:110 +0x3b4
github.com/gogits/gogs/cmd.runWeb(0x116c80a0, 0x0, 0x116c80a0)
	/tmp/go/src/github.com/gogits/gogs/cmd/web.go:166 +0x48
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0x8ab180, 0x9b5488, 0x116c80a0, 0x113ba000, 0x0)
	/tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0x94
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0x96d313, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x980bc1, 0x10, 0x0, ...)
	/tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0x7e0
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0x116bc000, 0x1130c0d0, 0x2, 0x2, 0x0, 0x0)
	/tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x564
main.main()
	/tmp/go/src/github.com/gogits/gogs/gogs.go:41 +0x26c

```

**Comment by Unknwon** [comment]
Merge thread into https://github.com/gogits/gogs/issues/4996.
