### ISSUE TITLE
Docker won't create/init files

### ISSUE THREAD

**Issue by ProJaCore** [gogits/gogs#4876]
I try to create a new docker container with the following commands on my Ubuntu xenial 16.04 machine:
```
docker pull gogs/gogs
docker run --name=gogs -p 10022:22 -p 10080:3000 -v /var/gogs:/data gogs/gogs
```
and the output is following:
```
usermod: no changes
Nov 19 17:42:47 syslogd started: BusyBox v1.25.1
Nov 19 17:42:47 sshd[29]: Server listening on :: port 22.
Nov 19 17:42:47 sshd[29]: Server listening on 0.0.0.0 port 22.
2017/11/19 17:42:47 [ WARN] Custom config '/data/gogs/conf/app.ini' not found, ignore this if you're running first time
2017/11/19 17:42:47 [TRACE] Custom path: /data/gogs
2017/11/19 17:42:47 [TRACE] Log path: /app/gogs/log
2017/11/19 17:42:47 [TRACE] Build Time: 2017-11-19 04:16:46 UTC
2017/11/19 17:42:47 [TRACE] Build Git Hash:
2017/11/19 17:42:47 [TRACE] Log Mode: Console (Trace)
2017/11/19 17:42:47 [ INFO] Gogs 0.11.33.1116
2017/11/19 17:42:47 [ INFO] Cache Service Enabled
2017/11/19 17:42:47 [ INFO] Session Service Enabled
2017/11/19 17:42:47 [ INFO] SQLite3 Supported
2017/11/19 17:42:47 [ INFO] Run Mode: Development
panic: fail to set message file(sk-SK): open conf/locale/locale_sk-SK.ini: no such file or directory

goroutine 1 [running]:
github.com/gogits/gogs/vendor/github.com/go-macaron/i18n.initLocales(0xc420128ad5, 0x0, 0xf8b4a5, 0xb, 0xc42084cb40, 0xc420c50220, 0x16, 0xc420147040, 0x1a, 0x1a, ...)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/i18n/i18n.go:57 +0x5ff
github.com/gogits/gogs/vendor/github.com/go-macaron/i18n.I18n(0xc4201b6600, 0x1, 0x1, 0xc420c50220, 0x16)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/go-macaron/i18n/i18n.go:158 +0xee
github.com/gogits/gogs/cmd.newMacaron(0xc420231180)
        /tmp/go/src/github.com/gogits/gogs/cmd/web.go:130 +0xab5
github.com/gogits/gogs/cmd.runWeb(0xc420231180, 0x0, 0xc420231180)
        /tmp/go/src/github.com/gogits/gogs/cmd/web.go:166 +0x74
github.com/gogits/gogs/vendor/github.com/urfave/cli.HandleAction(0xe631e0, 0xfc7d78, 0xc420231180, 0xc42017b500, 0x0)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:483 +0xb9
github.com/gogits/gogs/vendor/github.com/urfave/cli.Command.Run(0xf7ee8d, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf92aef, 0x10, 0x0, ...)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/gogits/gogs/vendor/github.com/urfave/cli.(*App).Run(0xc420146340, 0xc42000c140, 0x2, 0x2, 0x0, 0x0)
        /tmp/go/src/github.com/gogits/gogs/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
        /tmp/go/src/github.com/gogits/gogs/gogs.go:41 +0x3ea
2017/11/19 17:42:48 [ WARN] Custom config '/data/gogs/conf/app.ini' not found, ignore this if you're running first time
2017/11/19 17:42:48 [TRACE] Custom path: /data/gogs
2017/11/19 17:42:48 [TRACE] Log path: /app/gogs/log
2017/11/19 17:42:48 [TRACE] Build Time: 2017-11-19 04:16:46 UTC
2017/11/19 17:42:48 [TRACE] Build Git Hash:
2017/11/19 17:42:48 [TRACE] Log Mode: Console (Trace)
2017/11/19 17:42:48 [ INFO] Gogs 0.11.33.1116
2017/11/19 17:42:48 [ INFO] Cache Service Enabled
2017/11/19 17:42:48 [ INFO] Session Service Enabled
2017/11/19 17:42:48 [ INFO] SQLite3 Supported
2017/11/19 17:42:48 [ INFO] Run Mode: Development
panic: fail to set message file(sk-SK): open conf/locale/locale_sk-SK.ini: no such file or directory
```
and then it repeats from the line "goroutine 1 [running]:" again again and again...

**Comment by Unknwon** [comment]
Hi there, this should be fixed, please re-pull, sorry about any inconvenience.

**Comment by Unknwon** [comment]
The `latest` is still building, please wait for another few minutes... https://hub.docker.com/r/gogs/gogs/builds/

**Comment by ProJaCore** [comment]
Oh man thank you!
