### ISSUE TITLE
Occasional panic on user login

### ISSUE THREAD

**Issue by DerDackel** [gogits/gogs#692]
We've struggled with an issue for a few weeks now in our local Gogs deployment. Occasionally on user login the whole app will crash with a nil pointer dereference. This happens about once a day and I had hoped to be able to track down more info so I had delayed opening this issue, but I couldn't dig up additional info. I couldn't reproduce it or add any meaningful info, so all I have is a goroutine dump happening immediately after authentication.

All I can say at this point
 * All users this has happened on were authenticated using LDAP (but might be unrelated as pretty much only the root user isn't on LDAP.
 * It made no difference whether authentication was successful or not.
 * Authentication usually shows up in the macaron log as the last thing before the crash.
 * I can't exactly trace back to when it started, but it has basically happened to us on any 0.5.x build, up to at least 0.5.7.1105 which we currently have deployed.

Here's the dump that is produced on crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x9349be]

goroutine 73 [running]:
runtime.panic(0xb347a0, 0x10a0eb3)
        /home/sjackel/opt/golang/current/src/pkg/runtime/panic.c:279 +0xf5
github.com/gogits/gogs/modules/asn1-ber.readBytes(0x0, 0x0, 0xc20873600e, 0x2, 0x2, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/asn1-ber/ber.go:181 +0xbe
github.com/gogits/gogs/modules/asn1-ber.ReadPacket(0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/asn1-ber/ber.go:194 +0xaf
github.com/gogits/gogs/modules/ldap.(*Conn).reader(0xc2082c6480)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/ldap/conn.go:259 +0xa5
created by github.com/gogits/gogs/modules/ldap.(*Conn).start
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/ldap/conn.go:83 +0x2f

goroutine 16 [IO wait]:
net.runtime_pollWait(0x7fc1b2a37e68, 0x72, 0x0)
        /home/sjackel/opt/golang/go-1.3.3/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc208603640, 0x72, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc208603640, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).accept(0xc2086035e0, 0xd5cdb0, 0x0, 0x7fc1b2a312b8, 0xb)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_unix.go:419 +0x343
net.(*TCPListener).AcceptTCP(0xc20841ec80, 0x5655e3, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/tcpsock_posix.go:234 +0x5d
net/http.tcpKeepAliveListener.Accept(0xc20841ec80, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1947 +0x4b
net/http.(*Server).Serve(0xc2085fe3c0, 0x7fc1b2a463a0, 0xc20841ec80, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1698 +0x91
net/http.(*Server).ListenAndServe(0xc2085fe3c0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1688 +0x14d
net/http.ListenAndServe(0xc20855c860, 0xc, 0x7fc1b2a46340, 0xc2081327e0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1778 +0x79
github.com/gogits/gogs/cmd.runWeb(0xc2080dc0b0)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/cmd/web.go:419 +0x1cfa
github.com/codegangsta/cli.Command.Run(0xbe9870, 0x3, 0x0, 0x0, 0xc3f790, 0x15, 0xcfccb0, 0x64, 0x0, 0x0, ...)
        /home/sjackel/opt/golibs/src/github.com/codegangsta/cli/command.go:101 +0xc6f
github.com/codegangsta/cli.(*App).Run(0xc208058000, 0xc20800e000, 0x2, 0x2, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/codegangsta/cli/app.go:125 +0x941
main.main()
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/gogs.go:41 +0x2bf

goroutine 19 [finalizer wait, 2 minutes]:
runtime.park(0x4138a0, 0x10d6940, 0x10a5d09)
        /home/sjackel/opt/golang/current/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x10d6940, 0x10a5d09)
        /home/sjackel/opt/golang/current/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /home/sjackel/opt/golang/current/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /home/sjackel/opt/golang/current/src/pkg/runtime/proc.c:1445

goroutine 20 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc20803b7c0)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/log/log.go:231 +0x2d8
created by github.com/gogits/gogs/modules/log.newLogger
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/log/log.go:161 +0xc4

goroutine 38 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc2081243c0)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/cron/cron.go:162 +0x90b
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/cron/cron.go:137 +0x3a

goroutine 32 [chan receive, 2 minutes]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/mailer/mailer.go:53 +0x68
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/mailer/mailer.go:47 +0xc2

goroutine 33 [select, 2 minutes]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208160040)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/log/log.go:231 +0x2d8
created by github.com/gogits/gogs/modules/log.newLogger
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/log/log.go:161 +0xc4

goroutine 37 [chan receive, 2 minutes]:
database/sql.(*DB).connectionOpener(0xc2081ca380)
        /home/sjackel/opt/golang/current/src/pkg/database/sql/sql.go:583 +0x48
created by database/sql.Open
        /home/sjackel/opt/golang/current/src/pkg/database/sql/sql.go:442 +0x27c

goroutine 39 [select, 2 minutes]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc2081982c0)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/log/log.go:231 +0x2d8
created by github.com/gogits/gogs/modules/log.newLogger
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/log/log.go:161 +0xc4

goroutine 70 [runnable]:
reflect.Value.call(0xa364a0, 0xd5cba0, 0x0, 0x130, 0xbc0af0, 0x4, 0xc2087427e0, 0x1, 0x1, 0x0, ...)
        /home/sjackel/opt/golang/current/src/pkg/reflect/value.go:501 +0xc0a
reflect.Value.Call(0xa364a0, 0xd5cba0, 0x0, 0x130, 0xc2087427e0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/reflect/value.go:411 +0xd7
text/template.(*state).evalCall(0xc208526840, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0xa364a0, 0xd5cba0, 0x0, 0x130, 0x7fc1b2a46848, ...)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:563 +0x9d4
text/template.(*state).evalFunction(0xc208526840, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0xc208478060, 0x7fc1b2a46848, 0xc20847ce70, 0xc20856e5f0, 0x1, ...)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:455 +0x343
text/template.(*state).evalCommand(0xc208526840, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0xc20847ce70, 0x9e7220, 0xc208747cb0, 0x0, 0x182, ...)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:359 +0x23e
text/template.(*state).evalPipeline(0xc208526840, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0xc208314cd0, 0x9e7220, 0xc208747cb0, 0x0, 0x182)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:332 +0x1be
text/template.(*state).walk(0xc208526840, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0x7fc1b2a320c0, 0xc2081f3360)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:167 +0x133
text/template.(*state).walk(0xc208526840, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0x7fc1b2a46800, 0xc208189920)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:175 +0x848
text/template.(*state).walkTemplate(0xc2085267c0, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0xc20842bda0)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:315 +0x37d
text/template.(*state).walk(0xc2085267c0, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0x7fc1b2a39778, 0xc20842bda0)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:180 +0x722
text/template.(*state).walk(0xc2085267c0, 0x9e26c0, 0xc20851f590, 0x0, 0x150, 0x7fc1b2a46800, 0xc20842bd40)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:175 +0x848
text/template.(*Template).Execute(0xc208379400, 0x7fc1b2a36678, 0xc2086039d0, 0x9e26c0, 0xc20851f590, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/text/template/exec.go:155 +0x332
html/template.(*Template).ExecuteTemplate(0xc2080da380, 0x7fc1b2a36678, 0xc2086039d0, 0xc68990, 0x10, 0x9e26c0, 0xc20851f590, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/html/template/template.go:87 +0xc4
github.com/Unknwon/macaron.(*TplRender).execute(0xc2085f7450, 0xc2080da380, 0xc68990, 0x10, 0x9e26c0, 0xc20851f590, 0xc20862c3f0, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/render.go:396 +0xc5
github.com/Unknwon/macaron.(*TplRender).renderBytes(0xc2085f7450, 0xbc1950, 0x7, 0xc68990, 0x10, 0x9e26c0, 0xc20851f590, 0x0, 0x0, 0x0, ...)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/render.go:431 +0x3c3
github.com/Unknwon/macaron.(*TplRender).renderHTML(0xc2085f7450, 0xc8, 0xbc1950, 0x7, 0xc68990, 0x10, 0x9e26c0, 0xc20851f590, 0x0, 0x0, ...)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/render.go:442 +0xcb
github.com/Unknwon/macaron.(*TplRender).HTMLSet(0xc2085f7450, 0xc8, 0xbc1950, 0x7, 0xc68990, 0x10, 0x9e26c0, 0xc20851f590, 0x0, 0x0, ...)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/render.go:460 +0xa5
github.com/Unknwon/macaron.(*Context).renderHTML(0xc208644460, 0xc8, 0xbc1950, 0x7, 0xc68990, 0x10, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/context.go:150 +0x120
github.com/Unknwon/macaron.(*Context).HTML(0xc208644460, 0xc8, 0xc68990, 0x10, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/context.go:161 +0x7f
github.com/gogits/gogs/modules/middleware.(*Context).HTML(0xc208660140, 0xc8, 0xc68990, 0x10)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/middleware/context.go:104 +0x55
github.com/gogits/gogs/modules/middleware.(*Context).RenderWithErr(0xc208660140, 0xc208714120, 0x2d, 0xc68990, 0x10, 0xac8f80, 0xc208664ae0)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/modules/middleware/context.go:114 +0xf1
github.com/gogits/gogs/routers/user.SignInPost(0xc208660140, 0xc2082c6d49, 0x7, 0xc20838e690, 0xe, 0x0)
        /home/sjackel/opt/golibs/src/github.com/gogits/gogs/routers/user/auth.go:107 +0x497
reflect.Value.call(0xa15b60, 0xd5c670, 0x0, 0x130, 0xbc0af0, 0x4, 0xc208527ac0, 0x2, 0x2, 0x0, ...)
        /home/sjackel/opt/golang/current/src/pkg/reflect/value.go:563 +0x1210
reflect.Value.Call(0xa15b60, 0xd5c670, 0x0, 0x130, 0xc208527ac0, 0x2, 0x2, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/reflect/value.go:411 +0xd7
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc20861bfc0, 0xa15b60, 0xd5c670, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x3b7
github.com/Unknwon/macaron.(*Context).run(0xc208644460)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/context.go:111 +0x94
github.com/Unknwon/macaron.(*Context).Next(0xc208644460)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/context.go:102 +0x32
github.com/Unknwon/macaron.func·008(0xc208644460, 0xc208144cd0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/recovery.go:160 +0x70
reflect.Value.call(0xa0b8e0, 0xd5bcf8, 0x0, 0x130, 0xbc0af0, 0x4, 0xc208526f40, 0x2, 0x2, 0x0, ...)
        /home/sjackel/opt/golang/current/src/pkg/reflect/value.go:563 +0x1210
reflect.Value.Call(0xa0b8e0, 0xd5bcf8, 0x0, 0x130, 0xc208526f40, 0x2, 0x2, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/reflect/value.go:411 +0xd7
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc20861bfc0, 0xa0b8e0, 0xd5bcf8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x3b7
github.com/Unknwon/macaron.(*Context).run(0xc208644460)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/context.go:111 +0x94
github.com/Unknwon/macaron.(*Context).Next(0xc208644460)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/context.go:102 +0x32
github.com/Unknwon/macaron.func·004(0x7fc1b2a46598, 0xc208526ec0, 0xc20815e750, 0xc208644460, 0xc208144cd0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/logger.go:40 +0x202
reflect.Value.call(0xabcd20, 0xd5bce8, 0x0, 0x130, 0xbc0af0, 0x4, 0xc2082c6a80, 0x4, 0x4, 0x0, ...)
        /home/sjackel/opt/golang/current/src/pkg/reflect/value.go:563 +0x1210
reflect.Value.Call(0xabcd20, 0xd5bce8, 0x0, 0x130, 0xc2082c6a80, 0x4, 0x4, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/reflect/value.go:411 +0xd7
github.com/Unknwon/macaron/inject.(*injector).Invoke(0xc20861bfc0, 0xabcd20, 0xd5bce8, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/inject/inject.go:102 +0x3b7
github.com/Unknwon/macaron.(*Context).run(0xc208644460)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/context.go:111 +0x94
github.com/Unknwon/macaron.func·015(0x7fc1b2a464a8, 0xc2086443c0, 0xc20815e750, 0x0)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/router.go:159 +0x19e
github.com/Unknwon/macaron.(*Router).ServeHTTP(0xc208198380, 0x7fc1b2a464a8, 0xc2086443c0, 0xc20815e750)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/router.go:246 +0x390
github.com/Unknwon/macaron.(*Macaron).ServeHTTP(0xc2081327e0, 0x7fc1b2a464a8, 0xc2086443c0, 0xc20815e750)
        /home/sjackel/opt/golibs/src/github.com/Unknwon/macaron/macaron.go:161 +0x14a
net/http.serverHandler.ServeHTTP(0xc2085fe3c0, 0x7fc1b2a464a8, 0xc2086443c0, 0xc20815e750)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1673 +0x19f
net/http.(*conn).serve(0xc2083e2480)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1174 +0xa7e
created by net/http.(*Server).Serve
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1721 +0x313

goroutine 71 [IO wait]:
net.runtime_pollWait(0x7fc1b2a37c58, 0x72, 0x0)
        /home/sjackel/opt/golang/go-1.3.3/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc2085840d0, 0x72, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc2085840d0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208584070, 0xc208592000, 0x1000, 0x1000, 0x0, 0x7fc1b2a312b8, 0xb)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc208586008, 0xc208592000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/net.go:122 +0xe7
net/http.(*liveSwitchReader).Read(0xc2083e25a8, 0xc208592000, 0x1000, 0x1000, 0xfc0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:206 +0xaf
io.(*LimitedReader).Read(0xc20858a060, 0xc208592000, 0x1000, 0x1000, 0x1d, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/io/io.go:399 +0xd0
bufio.(*Reader).fill(0xc20858c060)
        /home/sjackel/opt/golang/current/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).ReadSlice(0xc20858c060, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/bufio/bufio.go:298 +0x22c
bufio.(*Reader).ReadLine(0xc20858c060, 0x0, 0x0, 0x0, 0x422f00, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/bufio/bufio.go:326 +0x69
net/textproto.(*Reader).readLineSlice(0xc2083ada40, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/textproto/reader.go:55 +0x9d
net/textproto.(*Reader).ReadLine(0xc2083ada40, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/textproto/reader.go:36 +0x4e
net/http.ReadRequest(0xc20858c060, 0xc208100ea0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/request.go:556 +0xc7
net/http.(*conn).readRequest(0xc2083e2580, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:577 +0x276
net/http.(*conn).serve(0xc2083e2580)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1132 +0x61e
created by net/http.(*Server).Serve
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1721 +0x313

goroutine 151 [chan receive]:
github.com/macaron-contrib/cache.(*MemoryCache).vaccuum(0xc2080fe9f0)
        /home/sjackel/opt/golibs/src/github.com/macaron-contrib/cache/memory.go:204 +0x6b
created by github.com/macaron-contrib/cache.(*MemoryCache).StartAndGC
        /home/sjackel/opt/golibs/src/github.com/macaron-contrib/cache/memory.go:194 +0x328

goroutine 153 [IO wait]:
net.runtime_pollWait(0x7fc1b2a37db8, 0x72, 0x0)
        /home/sjackel/opt/golang/go-1.3.3/src/pkg/runtime/netpoll.goc:146 +0x66
net.(*pollDesc).Wait(0xc2086036b0, 0x72, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_poll_runtime.go:84 +0x46
net.(*pollDesc).WaitRead(0xc2086036b0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_poll_runtime.go:89 +0x42
net.(*netFD).Read(0xc208603650, 0xc20855e000, 0x1000, 0x1000, 0x0, 0x7fc1b2a312b8, 0xb)
        /home/sjackel/opt/golang/current/src/pkg/net/fd_unix.go:242 +0x34c
net.(*conn).Read(0xc20841ec88, 0xc20855e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/net.go:122 +0xe7
net/http.(*liveSwitchReader).Read(0xc2084e1828, 0xc20855e000, 0x1000, 0x1000, 0xfc0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:206 +0xaf
io.(*LimitedReader).Read(0xc2084a0ae0, 0xc20855e000, 0x1000, 0x1000, 0x1d, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/io/io.go:399 +0xd0
bufio.(*Reader).fill(0xc2085fe420)
        /home/sjackel/opt/golang/current/src/pkg/bufio/bufio.go:97 +0x1b3
bufio.(*Reader).ReadSlice(0xc2085fe420, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/bufio/bufio.go:298 +0x22c
bufio.(*Reader).ReadLine(0xc2085fe420, 0x0, 0x0, 0x0, 0x422f00, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/bufio/bufio.go:326 +0x69
net/textproto.(*Reader).readLineSlice(0xc2084b9740, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/textproto/reader.go:55 +0x9d
net/textproto.(*Reader).ReadLine(0xc2084b9740, 0x0, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/textproto/reader.go:36 +0x4e
net/http.ReadRequest(0xc2085fe420, 0xc208101790, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/request.go:556 +0xc7
net/http.(*conn).readRequest(0xc2084e1800, 0x0, 0x0, 0x0)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:577 +0x276
net/http.(*conn).serve(0xc2084e1800)
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1132 +0x61e
created by net/http.(*Server).Serve
        /home/sjackel/opt/golang/current/src/pkg/net/http/server.go:1721 +0x313

goroutine 161 [syscall]:
runtime.goexit()
        /home/sjackel/opt/golang/current/src/pkg/runtime/proc.c:1445
```

**Comment by blemasle** [comment]
I second that bug. In my case, ldap and gogs are on the same server so it seems unlikely that the connection can be loss during authentication.

**Comment by Unknwon** [comment]
@blemasle thanks for the info!

**Comment by Unknwon** [comment]
Should be fixed with improved implementation of LDAP.
