### ISSUE TITLE
Add prompt message to prevent user calls `gogs serv`

### ISSUE THREAD

**Issue by steelbrain** [gogits/gogs#863]
Gogs v0.5.11
Ubuntu 14.04 -- Linux Mint 17.1
Git v1.9.1
```
$ ./gogs serv
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gogits/gogs/cmd.runServ(0xc208110180)
        /root/go/src/github.com/gogits/gogs/cmd/serve.go:82 +0x2c17
github.com/codegangsta/cli.Command.Run(0xd5faf0, 0x4, 0x0, 0x0, 0xe4f2f0, 0x2f, 0xe4f1b0, 0x29, 0x0, 0x0, ...)
        /root/go/src/github.com/codegangsta/cli/command.go:101 +0xd6a
github.com/codegangsta/cli.(*App).Run(0xc20801fad0, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /root/go/src/github.com/codegangsta/cli/app.go:154 +0xbab
main.main()
        /root/go/src/github.com/gogits/gogs/gogs.go:41 +0x397

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc20803a040)
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 7 [runnable]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208120f80)
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:229
created by github.com/gogits/gogs/modules/log.newLogger
        /root/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 8 [runnable]:
database/sql.(*DB).connectionOpener(0xc2080a7540)
        /usr/src/go/src/database/sql/sql.go:588
created by database/sql.Open
        /usr/src/go/src/database/sql/sql.go:452 +0x31c
```

**Comment by Unknwon** [comment]
`gogs serv` should never be called by hand. Maybe add a prompt message is better than panic info.

**Comment by steelbrain** [comment]
Actually, Gog's SSH server was not working, so I thought that if `gogs http` starts the http server, then maybe `gogs serv` starts the ssh server.

**Comment by lunny** [comment]
add a prompt message is necessary

**Comment by Unknwon** [comment]
> Gog's SSH server was not working

Gogs does not have SSH server, it uses system's SSH server, usually OpenSSH.

You can report on SSH connection issue with error message or any related info would be helpful!

**Comment by Unknwon** [comment]
This should have been fixed with more friendly message.
