### ISSUE TITLE
更新报错问题

### ISSUE THREAD

**Issue by Arylo** [gogits/gogs#873]
原本的版本是v0.5.5_linux
更新程序最新v0.5.11_linux , 出现报错, 还原为V0.5.5_linux则无此报错
(更新v0.5.9_linux也出现同样现象)
```
2015/01/27 10:15:40 [T] Custom path: /opt/gogs/custom
2015/01/27 10:15:40 [T] Log path: /opt/gogs/log
2015/01/27 10:15:40 [I] Gogs: Go Git Service 0.5.9.1213 Beta
2015/01/27 10:15:40 [I] Log Mode: Console(Trace)
2015/01/27 10:15:40 [I] Redis Enabled
2015/01/27 10:15:40 [I] Memcache Enabled
2015/01/27 10:15:40 [I] Cache Service Enabled
2015/01/27 10:15:40 [I] Session Service Enabled
2015/01/27 10:15:40 [I] SQLite3 Enabled
2015/01/27 10:15:40 [I] Run Mode: Production
panic: template: user/dashboard:21: function "ActionDesc" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0x7f623ce52580, 0xc2084a3a80, 0x0)
        /usr/local/go/src/html/template/template.go:304 +0x50
github.com/Unknwon/macaron.compile(0xc2081882c0, 0x13, 0x0, 0x0, 0xc2081882e0, 0x2, 0x2, 0xc2081ca010, 0x1, 0x1, ...)
        /home/wuwen/Applications/go/src/github.com/Unknwon/macaron/render.go:245 +0x400
github.com/Unknwon/macaron.(*templateSet).Set(0xc208084420, 0xccf900, 0x7, 0xc20810e1c0, 0x0)
        /home/wuwen/Applications/go/src/github.com/Unknwon/macaron/render.go:270 +0x51
github.com/Unknwon/macaron.renderHandler(0xc2081882c0, 0x13, 0x0, 0x0, 0xc2081882e0, 0x2, 0x2, 0xc2081ca010, 0x1, 0x1, ...)
        /home/wuwen/Applications/go/src/github.com/Unknwon/macaron/render.go:340 +0x248
github.com/Unknwon/macaron.Renderer(0xc20847d440, 0x1, 0x1, 0x0, 0x0)
        /home/wuwen/Applications/go/src/github.com/Unknwon/macaron/render.go:377 +0xea
github.com/gogits/gogs/cmd.newMacaron(0x55f990)
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/cmd/web.go:112 +0x6a2
github.com/gogits/gogs/cmd.runWeb(0xc208086180)
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/cmd/web.go:162 +0x34
github.com/codegangsta/cli.Command.Run(0xcf93e0, 0x3, 0x0, 0x0, 0xd55e90, 0x15, 0xe25d90, 0x64, 0x0, 0x0, ...)
        /home/wuwen/Applications/go/src/github.com/codegangsta/cli/command.go:101 +0xd6a
github.com/codegangsta/cli.(*App).Run(0xc20801f860, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /home/wuwen/Applications/go/src/github.com/codegangsta/cli/app.go:154 +0xbab
main.main()
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/gogs.go:41 +0x397

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208070000)
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 7 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:53                                               +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/mailer/mailer.go:47                                               +0xd1

goroutine 8 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc208135040)
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 183 [chan send]:
text/template/parse.lexSpace(0xc2083dea80, 0xe85370)
        /usr/local/go/src/text/template/parse/lex.go:339 +0xdd
text/template/parse.(*lexer).run(0xc2083dea80)
        /usr/local/go/src/text/template/parse/lex.go:198 +0x5d
created by text/template/parse.lex
        /usr/local/go/src/text/template/parse/lex.go:191 +0x1ac

goroutine 12 [select]:
github.com/gogits/gogs/modules/cron.(*Cron).run(0xc20807cac0)
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/cron/cron.go:162 +0xa65
created by github.com/gogits/gogs/modules/cron.(*Cron).Start
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/cron/cron.go:137 +0x3d

goroutine 19 [chan receive]:
database/sql.(*DB).connectionOpener(0xc208076460)
        /usr/local/go/src/database/sql/sql.go:589 +0x4c
created by database/sql.Open
        /usr/local/go/src/database/sql/sql.go:452 +0x31c

goroutine 49 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 13 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc20807df80)
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /home/wuwen/Applications/go/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a
```

**Comment by Unknwon** [comment]
You should delete old template files first, then move the new ones to old position.

**Comment by Unknwon** [comment]
reopen if you want to continue discussing.
