### ISSUE TITLE
panic: template: issue/milestone:35: function "str2html" not define

### ISSUE THREAD

**Issue by Spy-Seth** [gogits/gogs#995]
Hello,

I'm trying to update my old gogs instance to the latest version (and switch to the debian package by the same way). When I run `/etc/init.g/gogs start`, gogs crash and log this in the log file:

```
2015/02/28 19:16:37 ^[[1;36m[T] Custom path: /opt/gogs/custom^[[0m
2015/02/28 19:16:37 ^[[1;36m[T] Log path: /opt/gogs/log^[[0m
2015/02/28 19:16:37 ^[[1;32m[I] Gogs: Go Git Service 0.5.13.0214 Beta^[[0m
2015/02/28 19:16:37 ^[[1;32m[I] Log Mode: Console(Trace)^[[0m
2015/02/28 19:16:37 ^[[1;32m[I] Cache Service Enabled^[[0m
2015/02/28 19:16:37 ^[[1;32m[I] Session Service Enabled^[[0m
2015/02/28 19:16:37 ^[[1;32m[I] Run Mode: Production^[[0m
panic: template: issue/milestone:35: function "str2html" not defined

goroutine 1 [running]:
html/template.Must(0x0, 0x7f1046647400, 0xc20814e4c0, 0x0)
        /usr/local/go/src/html/template/template.go:304 +0x50
github.com/Unknwon/macaron.compile(0xc2081c8420, 0x13, 0x0, 0x0, 0xc2081c8440, 0x2, 0x2, 0xc2081e0010, 0x1, 0x1, ...)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/Unknwon/macaron/render.go:245 +0x400
github.com/Unknwon/macaron.(*templateSet).Set(0xc2081c67e0, 0xc62da0, 0x7, 0xc2080c4000, 0x0)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/Unknwon/macaron/render.go:270 +0x51
github.com/Unknwon/macaron.renderHandler(0xc2081c8420, 0x13, 0x0, 0x0, 0xc2081c8440, 0x2, 0x2, 0xc2081e0010, 0x1, 0x1, ...)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/Unknwon/macaron/render.go:337 +0x248
github.com/Unknwon/macaron.Renderer(0xc2081a52f0, 0x1, 0x1, 0x0, 0x0)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/Unknwon/macaron/render.go:374 +0xea
github.com/gogits/gogs/cmd.newMacaron(0xc2080c6300)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/gogits/gogs/cmd/web.go:125 +0x6a2
github.com/gogits/gogs/cmd.runWeb(0xc2080c6300)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/gogits/gogs/cmd/web.go:175 +0xbe
github.com/codegangsta/cli.Command.Run(0xc8c660, 0x3, 0x0, 0x0, 0xceabb0, 0x15, 0xdbb790, 0x64, 0x0, 0x0, ...)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/codegangsta/cli/command.go:113 +0x1038
github.com/codegangsta/cli.(*App).Run(0xc20817b110, 0xc20800a000, 0x2, 0x2, 0x0, 0x0)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/codegangsta/cli/app.go:156 +0xcf7
main.main()
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/main/gogs.go:40 +0x367

goroutine 5 [select]:
github.com/gogits/gogs/modules/log.(*Logger).StartLogger(0xc20803b5c0)
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log/log.go:231 +0x369
created by github.com/gogits/gogs/modules/log.newLogger
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/log/log.go:161 +0x13a

goroutine 17 [chan receive]:
github.com/gogits/gogs/modules/mailer.processMailQueue()
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/mailer/mailer.go:52 +0x69
created by github.com/gogits/gogs/modules/mailer.NewMailerContext
        /tmp/d20150216-14-g529xn/opt/gogs/.heroku/g/src/github.com/gogits/gogs/modules/mailer/mailer.go:46 +0xea
```

**Comment by Unknwon** [comment]
Hi there, thanks your feedback!

This error looks like you didn't remove `templates` directory before you copy the new ones in as described here: http://gogs.io/docs/installation/install_from_binary.html

**Comment by Spy-Seth** [comment]
You right I do nothing. I'm trying to install gogs from the debian package (http://gogs.io/docs/installation/install_from_packages.html). 

So I move my old installation away, and re-install the package and now it's works. Thanks for the tips.

**Comment by Unknwon** [comment]
Great!
